### ISSUE TITLE
【每日一题】- 2019-08-11 - 547.朋友圈

### ISSUE THREAD

**Issue by 3460741663** [azl397985856/leetcode#100]
班上有 N 名学生。其中有些人是朋友，有些则不是。他们的友谊具有是传递性。如果已知 A 是 B 的朋友，B 是 C 的朋友，那么我们可以认为 A 也是 C 的朋友。所谓的朋友圈，是指所有朋友的集合。

给定一个 N * N 的矩阵 M，表示班级中学生之间的朋友关系。如果M[i][j] = 1，表示已知第 i 个和 j 个学生互为朋友关系，否则为不知道。你必须输出所有学生中的已知的朋友圈总数。

示例 1:

输入: 
[[1,1,0],
 [1,1,0],
 [0,0,1]]
输出: 2 
说明：已知学生0和学生1互为朋友，他们在一个朋友圈。
第2个学生自己在一个朋友圈。所以返回2。
示例 2:

输入: 
[[1,1,0],
 [1,1,1],
 [0,1,1]]
输出: 1
说明：已知学生0和学生1互为朋友，学生1和学生2互为朋友，所以学生0和学生2也是朋友，所以他们三个在一个朋友圈，返回1。
注意：

N 在[1,200]的范围内。
对于所有学生，有M[i][i] = 1。
如果有M[i][j] = 1，则有M[j][i] = 1。

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/friend-circles
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by 3460741663** [comment]
认领

**Comment by snowan** [comment]
我添加english version吧?

**Comment by azl397985856** [comment]
> 我添加english version吧?

好的啊

**Comment by xiongcaihu** [comment]
``` .js
/**
 * @param {number[][]} M
 * @return {number}
 * 
 * 首先第一个肯定是一个圈子
 * 然后依次遍历第二个人，第三个人
 * 
 * 每遍历到一个人，都判断它和已经有的圈子的人是否是好友
 * 如果它和多个圈子的人是好友，那么合并多个圈子
 * 
 * 如果不是，那么它自己单独成为一个圈子
 */
var findCircleNum = function (M) {
    var quan = [
        [0]
    ];
    for (var i = 1; i < M.length; i++) {
        var belong = {};
        for (var j = 0; j < quan.length; j++) {
            for (var n = 0; n < quan[j].length; n++) {
                var nowFriend = quan[j][n];
                if (M[i][nowFriend] == 1 || M[nowFriend][i] == 1) {
                    belong[j] = 1;
                    break;
                }
            }
        }
        if (belong.length == 0) {
            quan.push([i]);
        } else {
            var temp = [];
            var newQuan = [];
            quan.forEach((item, index) => {
                if (!belong[index]) {
                    newQuan.push(item);
                } else {
                    temp.push(...item);
                }
            })
            temp.push(i);
            newQuan.push(temp);
            quan = newQuan;
        }
    }
    return quan.length;
};
```

**Comment by azl397985856** [comment]
> ```js
> /**
>  * @param {number[][]} M
>  * @return {number}
>  * 
>  * 首先第一个肯定是一个圈子
>  * 然后依次遍历第二个人，第三个人
>  * 
>  * 每遍历到一个人，都判断它和已经有的圈子的人是否是好友
>  * 如果它和多个圈子的人是好友，那么合并多个圈子
>  * 
>  * 如果不是，那么它自己单独成为一个圈子
>  */
> var findCircleNum = function (M) {
>     var quan = [
>         [0]
>     ];
>     for (var i = 1; i < M.length; i++) {
>         var belong = {};
>         for (var j = 0; j < quan.length; j++) {
>             for (var n = 0; n < quan[j].length; n++) {
>                 var nowFriend = quan[j][n];
>                 if (M[i][nowFriend] == 1 || M[nowFriend][i] == 1) {
>                     belong[j] = 1;
>                     break;
>                 }
>             }
>         }
>         if (belong.length == 0) {
>             quan.push([i]);
>         } else {
>             var temp = [];
>             var newQuan = [];
>             quan.forEach((item, index) => {
>                 if (!belong[index]) {
>                     newQuan.push(item);
>                 } else {
>                     temp.push(...item);
>                 }
>             })
>             temp.push(i);
>             newQuan.push(temp);
>             quan = newQuan;
>         }
>     }
>     return quan.length;
> };
> ```

你的命名要笑死我啊

**Comment by azl397985856** [comment]
英文版： https://github.com/azl397985856/leetcode/blob/master/problems/547.friend-circles-en.md
