### ISSUE TITLE
【每日一题】- 2019-08-16 - 字符串首位相等的最长子串

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#116]
求一个字符串首尾相等的最长子串，例如abcba，最长就是abcba

**Comment by xiongcaihu** [comment]
``` .js
function hehe(str) {
    if (str.length == 0) return '';
    var map = {};
    var maxLen = 1;
    var maxChar = str[0];
    for (var i = 0; i < str.length; i++) {
        var char = str[i];
        if (map[char] != null) {
            if (i - map[char] + 1 > maxLen) {
                maxLen = i - map[char] + 1;
                maxChar = char;
            }
        } else {
            map[char] = i;
        }
    }

    return str.slice(map[maxChar], map[maxChar] + maxLen);
}
```

**Comment by azl397985856** [comment]
> ```js
> function hehe(str) {
>     if (str.length == 0) return '';
>     var map = {};
>     var maxLen = 1;
>     var maxChar = str[0];
>     for (var i = 0; i < str.length; i++) {
>         var char = str[i];
>         if (map[char] != null) {
>             if (i - map[char] + 1 > maxLen) {
>                 maxLen = i - map[char] + 1;
>                 maxChar = char;
>             }
>         } else {
>             map[char] = i;
>         }
>     }
> 
>     return str.slice(map[maxChar], map[maxChar] + maxLen);
> }
> ```

每次看你代码我都想哭T﹏T😭

**Comment by azl397985856** [comment]
基本思路：

用一个hashmap去存储每一个字符第一次出现位置，遍历过程中如果当前字符出现过，算出当前长度 判断是否最长

**Comment by jinwei14** [comment]
这个思路有问题吧 ？可以过么

**Comment by azl397985856** [comment]
> 这个思路有问题吧 ？可以过么

说出你的想法
