### ISSUE TITLE
121.best-time-to-buy-and-sell-stock.md 是不是不对？

### ISSUE THREAD

**Issue by Dcell** [azl397985856/leetcode#12]
121.best-time-to-buy-and-sell-stock.md 是不是不对？
低点买入，高点卖出？
不是应该 1点买入；6点卖出么？
还是我理解错了？

**Comment by Dcell** [comment]
但是老哥说：`如下图，我们只需要求出加粗部分的最大值即可`；这句话是不是描述错了？

**Comment by azl397985856** [comment]
你觉得怎么描述才对

**Comment by Dcell** [comment]
Em... 就如图看，加粗的部分的最大值其实并不是最大收益，不是么
看了老哥的答案：
1.以更小的min值为分割点，划分多个区域；
2.每个区域的最大收益，为最终最大收益

![未命名表单](https://user-images.githubusercontent.com/4684864/57509568-20ab3f00-7337-11e9-84ff-5d10dd8e5878.png)

**Comment by azl397985856** [comment]
不是啊，你这个区间划分有问题，我们只关心上升的波峰波谷差，因此上图不区间划分不对
