### ISSUE TITLE
编程语言

### ISSUE THREAD

**Issue by yahyalxl** [azl397985856/leetcode#13]
编程语言有C/C++版的吗? 老哥

**Comment by azl397985856** [comment]
short answer is working in progress. BTW,  maybe you have to wait for a long time if there is no vounteers involved

**Comment by azl397985856** [comment]
#17

**Comment by raof01** [comment]
我可以提供C/C++版的，但是不知道大概的efforts是多少，具体到每天需要多少efforts

**Comment by azl397985856** [comment]
> 我可以提供C/C++版的，但是不知道大概的efforts是多少，具体到每天需要多少efforts

不做要求，只要符合规范，都会直接采纳。一点一滴我们都非常欢迎，如果想跟上节奏得话，可能一星期3道左右吧   (拍脑袋的)

**Comment by raof01** [comment]
> > 我可以提供C/C++版的，但是不知道大概的efforts是多少，具体到每天需要多少efforts
> 
> 不做要求，只要符合规范，都会直接采纳。一点一滴我们都非常欢迎，如果想跟上节奏得话，可能一星期3道左右吧 (拍脑袋的)

我先试试吧。“符合规范”是指LeetCode AC？

**Comment by my-hello-world** [comment]
哭 没有python啊

**Comment by liuyongtao** [comment]
我感觉语言是次要的，实现思路更重要吧。

**Comment by my-hello-world** [comment]
@liuyongtao  你说的对，但有时候思路不太理解，代码辅助的时候就比较吃力

**Comment by azl397985856** [comment]
> > > 我可以提供C/C++版的，但是不知道大概的efforts是多少，具体到每天需要多少efforts
> > 
> > 
> > 不做要求，只要符合规范，都会直接采纳。一点一滴我们都非常欢迎，如果想跟上节奏得话，可能一星期3道左右吧 (拍脑袋的)
> 
> 我先试试吧。“符合规范”是指LeetCode AC？

ac是最基本的，其次思路要和我一致（即大的思路和JS代码不能相差太多，比如JS用DFS，c++却用了dp）

**Comment by azl397985856** [comment]
> 我感觉语言是次要的，实现思路更重要吧。

语言只是辅助作用，看自己熟悉的语言理解的更快而已

**Comment by azl397985856** [comment]
> 哭 没有python啊

现在有了
