### ISSUE TITLE
【每日一题】- 2019-08-21 - 桶中取黑白球

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#132]

**Comment by azl397985856** [comment]
有两个桶，里面有白球，黑球各100个，你必须用以下规则将球取出来：

1. 每次从桶里取两个球
2. 如果两个球是相同的颜色，那么再放一个黑球
3. 如果两个球是不同的颜色，那么再放一个白球。

问：最后一个球是黑球的概率是多少？

**Comment by catbaron0** [comment]
问题表述有些令人费解。
> 有两个桶，里面有白球，黑球各100个
共有 200 颗球，或共有 400 颗球？
> 每次从桶里取两个球
随机从一个桶里取两颗球？从每个桶里各取两颗球？从每个桶里各取一个球？

**Comment by lvguofeng1303** [comment]
认领

**Comment by azl397985856** [comment]
> 认领

done
