### ISSUE TITLE
【每日一题】- 2019-08-29 - 854. 相似度为 K 的字符串

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#153]
如果可以通过将 A 中的两个小写字母精确地交换位置 K 次得到与 B 相等的字符串，我们称字符串 A 和 B 的相似度为 K（K 为非负整数）。

给定两个字母异位词 A 和 B ，返回 A 和 B 的相似度 K 的最小值。

 

示例 1：

输入：A = "ab", B = "ba"
输出：1
示例 2：

输入：A = "abc", B = "bca"
输出：2
示例 3：

输入：A = "abac", B = "baca"
输出：2
示例 4：

输入：A = "aabc", B = "abca"
输出：2
 

提示：

1 <= A.length == B.length <= 20
A 和 B 只包含集合 {'a', 'b', 'c', 'd', 'e', 'f'} 中的小写字母。

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/k-similar-strings
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by xiongcaihu** [comment]
``` .js
/**
 * @param {string} A
 * @param {string} B
 * @return {number}
 */
var kSimilarity = function(A, B) {
	var map = {};

	return temp(0, A);

	function temp(start, tA) {
		if (start == tA.length) {
			return 0;
		}
		if (map[tA]) {
			return map[tA];
		}
		if (tA[start] == B[start]) {
			return temp(start + 1, tA);
		} else {
			var min = Infinity;
			for (var i = start + 1; i < tA.length; i++) {
				if (tA[i] == B[start]) {
					var newA =
						tA.substring(0, start) +
						tA[i] +
						tA.substring(start + 1, i) +
						tA[start] +
						tA.substring(i + 1);
					min = Math.min(min, 1 + temp(start + 1, newA));
				}
			}
			map[tA] = min;
			return min;
		}
	}
};
```

![image](https://user-images.githubusercontent.com/10113078/63906739-96a0f680-ca4b-11e9-8412-8e21d16685d8.png)
