### ISSUE TITLE
【每日一题】- 2019-09-06 -如何利用已知random()函数，求一个1~N的全排列？

### ISSUE THREAD

**Issue by aleafboat** [azl397985856/leetcode#166]
输入N，利用random()函数，生成一个1至N的全排列。

例如：当输入N = 4,生成结果可以为1324或3214等等，并保证等概率

要求：
空间复杂度 o(n)
时间复杂度越少越好。
一次只需要生成一次随机的全排列，每次可能都不一样。
来源 算法导论

**Comment by azl397985856** [comment]
和2019-07-19  的题目重复
