### ISSUE TITLE
【每日一题】- 2019-09-16 - 165. 比较版本号

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#174]
比较两个版本号 version1 和 version2。
如果 version1 > version2 返回 1，如果 version1 < version2 返回 -1， 除此之外返回 0。

你可以假设版本字符串非空，并且只包含数字和 . 字符。

 . 字符不代表小数点，而是用于分隔数字序列。

例如，2.5 不是“两个半”，也不是“差一半到三”，而是第二版中的第五个小版本。

你可以假设版本号的每一级的默认修订版号为 0。例如，版本号 3.4 的第一级（大版本）和第二级（小版本）修订号分别为 3 和 4。其第三级和第四级修订号均为 0。
 

示例 1:

输入: version1 = "0.1", version2 = "1.1"
输出: -1
示例 2:

输入: version1 = "1.0.1", version2 = "1"
输出: 1
示例 3:

输入: version1 = "7.5.2.4", version2 = "7.5.3"
输出: -1
示例 4：

输入：version1 = "1.01", version2 = "1.001"
输出：0
解释：忽略前导零，“01” 和 “001” 表示相同的数字 “1”。
示例 5：

输入：version1 = "1.0", version2 = "1.0.0"
输出：0
解释：version1 没有第三级修订号，这意味着它的第三级修订号默认为 “0”。
 

提示：

版本字符串由以点 （.） 分隔的数字字符串组成。这个数字字符串可能有前导零。
版本字符串不以点开始或结束，并且其中不会有两个连续的点。

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/compare-version-numbers
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by yjua** [comment]
转换成数字大小进行比较
```js
function compareVersion(v1,v2){
    v1 = v1.split('.');
    v2 = v2.split('.');
    let len = v1.length > v2.length ? v1.length : v2.length;
    let num1 = 0,num2 = 0;
    for(let i = 0; i < len; i++){
        if(v1[i] !== undefined){
            num1 += parseInt(v1[i]) * Math.pow(10,len-1-i);
        }
        if(v2[i] !== undefined){
            num2 += parseInt(v2[i]) * Math.pow(10,len-1-i);
        }
    }
    let result = num1 - num2;
    return result > 0 ? 1 : (result == 0 ? 0 : -1);
}
```

**Comment by lvguofeng1303** [comment]
认领

**Comment by xiongcaihu** [comment]
> 思路
> 转换成数字，再进行比较
由于版本号是这样的格式 *.*.*.*，且每一位都是0-9，或者是有前导0的组合，比如001，002，所以可以用一个四位数表示，去除前导0用parseInt即可。

``` .js
/**
 * @param {string} version1
 * @param {string} version2
 * @return {number}
 */
var compareVersion = function (version1, version2) {
    var a = 0,
        b = 0;
    version1.split(".").forEach((item, index) => {
        a += parseInt(item) * 10 ** (3 - index)
    });

    version2.split(".").forEach((item, index) => {
        b += parseInt(item) * 10 ** (3 - index)
    });

    return a > b ? 1 : a == b ? 0 : -1;
};
```

![image](https://user-images.githubusercontent.com/10113078/64945118-78882280-d8a2-11e9-9cde-805d00b53b29.png)
