### ISSUE TITLE
【每日一题】- 2019-09-16 - 统计城市的所有灯泡

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#178]
这个是我刚毕业的时候，一个真实的面试题，这是一个开放题。

题目描述：

想办法，将一个城市的所有灯泡数量统计出来。

**Comment by BrucePhoebus** [comment]
费米估算法
1、如果某个城市常驻人口有1000万
2、假设每5人居住在一套房里，每套房有灯泡5只，那么住宅灯泡共有1000万只
3、假设公众场所每10人共享一只灯泡，那么共有100万只
4、主要的这两者相加就得出了1100万只
当然实际上这是估算的，具体应该还有一些商业建筑、工厂等部分，包含越多越接近真实值

**Comment by azl397985856** [comment]
> 费米估算法
> 1、如果某个城市常驻人口有1000万
> 2、假设每5人居住在一套房里，每套房有灯泡5只，那么住宅灯泡共有1000万只
> 3、假设公众场所每10人共享一只灯泡，那么共有100万只
> 4、主要的这两者相加就得出了1100万只
> 当然实际上这是估算的，具体应该还有一些商业建筑、工厂等部分，包含越多越接近真实值

开放问题，自圆其说就行。  但是能否更精确一点，换句话说如何证明你的数字相对误差不是特别大(不是那种数量级的差别)

**Comment by BrucePhoebus** [comment]
> > 费米估算法
> > 1、如果某个城市常驻人口有1000万
> > 2、假设每5人居住在一套房里，每套房有灯泡5只，那么住宅灯泡共有1000万只
> > 3、假设公众场所每10人共享一只灯泡，那么共有100万只
> > 4、主要的这两者相加就得出了1100万只
> > 当然实际上这是估算的，具体应该还有一些商业建筑、工厂等部分，包含越多越接近真实值
> 
> 开放问题，自圆其说就行。 但是能否更精确一点，换句话说如何证明你的数字相对误差不是特别大(不是那种数量级的差别)

当然，我这个水分多了点，实际上如果要保持一个量级需要从更精确的角度分析
例如
1、假设广州有1000万个居住单位，每个居住单位有10个灯泡，也就是有1亿个灯泡
2、假设有2万个公共建筑，那么假设一个公共建筑有10000个灯泡，那么就有1亿个灯泡
3、假设有10000公里街道，每个街道包括霓虹灯、红路灯。。。等有10000个，那么又有1亿个灯泡
4、假设有10万栋办公楼+酒店等，每栋平均20层，每层平均有500个灯泡，那么大概总共有10亿个灯泡
5、假设商户的商业建筑有100万间，每间大概有100个灯泡，大概1亿个灯泡
6、假设机动车+公共车等共有300万辆，每辆平均有10个灯泡，那么大概有3000万个
这么算下来，也就是总共有14亿3千万，也就是大概数十亿个灯泡，只有多没有少
