### ISSUE TITLE
【每日一题】- 2019-09-24 - 16. 最接近的三数之和

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#186]
这个和三数和很像，前几天我刚在微信公众号发了这个题目，今天我们就来看下这道类似的题

## 题目描述
给定一个包括 n 个整数的数组 nums 和 一个目标值 target。找出 nums 中的三个整数，使得它们的和与 target 最接近。返回这三个数的和。假定每组输入只存在唯一答案。

例如，给定数组 nums = [-1，2，1，-4], 和 target = 1.

与 target 最接近的三个数的和为 2. (-1 + 2 + 1 = 2).

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/3sum-closest
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by aleafboat** [comment]
golang版本
~~~
func threeSumClosest(nums []int, target int) int {
	if len(nums) < 3 {
		return -1
	}
	sort.Ints(nums)

	closest := nums[0] + nums[1] + nums[2] // result

	for i := 0; i < len(nums); i++ {
		start := i + 1
		end := len(nums) - 1
		for start < end {
			sum := nums[i] + nums[start] + nums[end]
			if math.Abs(float64(target)-float64(closest)) > math.Abs(float64(target)-float64(sum)) {
				closest = sum
			}
			if closest == target {
				return closest
			}
			if sum > target {
				end-- //greater then target
			} else {
				start++ //less then target
			}
		}

	}
	return closest

}
~~~

**Comment by azl397985856** [comment]
> golang版本
> 
> ```
> func threeSumClosest(nums []int, target int) int {
> 	if len(nums) < 3 {
> 		return -1
> 	}
> 	sort.Ints(nums)
> 
> 	closest := nums[0] + nums[1] + nums[2] // result
> 
> 	for i := 0; i < len(nums); i++ {
> 		start := i + 1
> 		end := len(nums) - 1
> 		for start < end {
> 			sum := nums[i] + nums[start] + nums[end]
> 			if math.Abs(float64(target)-float64(closest)) > math.Abs(float64(target)-float64(sum)) {
> 				closest = sum
> 			}
> 			if closest == target {
> 				return closest
> 			}
> 			if sum > target {
> 				end-- //greater then target
> 			} else {
> 				start++ //less then target
> 			}
> 		}
> 
> 	}
> 	return closest
> 
> }
> ```

有没有兴趣领取下题目？领取方式： https://github.com/azl397985856/leetcode/tree/master/daily
