### ISSUE TITLE
【每日一题】- 2019-10-08 - 72. 编辑距离

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#195]
给定两个单词 word1 和 word2，计算出将 word1 转换成 word2 所使用的最少操作数 。

你可以对一个单词进行如下三种操作：

插入一个字符
删除一个字符
替换一个字符
示例 1:

输入: word1 = "horse", word2 = "ros"
输出: 3
解释: 
horse -> rorse (将 'h' 替换为 'r')
rorse -> rose (删除 'r')
rose -> ros (删除 'e')
示例 2:

输入: word1 = "intention", word2 = "execution"
输出: 5
解释: 
intention -> inention (删除 't')
inention -> enention (将 'i' 替换为 'e')
enention -> exention (将 'n' 替换为 'x')
exention -> exection (将 'n' 替换为 'c')
exection -> execution (插入 'u')

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/edit-distance
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by aleafboat** [comment]
golang
~~~
func minDistance(word1 string, word2 string) int {

	n := len(word1)
	m := len(word2)
	dp := make([][]int, n+1) // 定义 dp[i][j] 是字符串 word1[0..i - 1] 到 word2[0..j - 1] 最小编辑距离
	for i := range dp {
		dp[i] = make([]int, m+1)
	}
	// 默认值
	for i := 0; i <= n; i++ {
		dp[i][0] = i
	}
	for j := 0; j <= m; j++ {
		dp[0][j] = j
	}

	for i := 1; i <= n; i++ {
		for j := 1; j <= m; j++ {
			if word1[i-1] == word2[j-1] {
				dp[i][j] = dp[i-1][j-1]
			} else {
				dp[i][j] = 1 + min(dp[i-1][j-1], min(dp[i-1][j], dp[i][j-1]))
				//其中，dp[i-1][j-1] 表示替换操作，dp[i-1][j] 表示删除操作，dp[i][j-1] 表示插入操作
			}

		}
	}
	return dp[n][m]
}
~~~

**Comment by azl397985856** [comment]
> golang
> 
> ```
> func minDistance(word1 string, word2 string) int {
> 
> 	n := len(word1)
> 	m := len(word2)
> 	dp := make([][]int, n+1) // 定义 dp[i][j] 是字符串 word1[0..i - 1] 到 word2[0..j - 1] 最小编辑距离
> 	for i := range dp {
> 		dp[i] = make([]int, m+1)
> 	}
> 	// 默认值
> 	for i := 0; i <= n; i++ {
> 		dp[i][0] = i
> 	}
> 	for j := 0; j <= m; j++ {
> 		dp[0][j] = j
> 	}
> 
> 	for i := 1; i <= n; i++ {
> 		for j := 1; j <= m; j++ {
> 			if word1[i-1] == word2[j-1] {
> 				dp[i][j] = dp[i-1][j-1]
> 			} else {
> 				dp[i][j] = 1 + min(dp[i-1][j-1], min(dp[i-1][j], dp[i][j-1]))
> 				//其中，dp[i-1][j-1] 表示替换操作，dp[i-1][j] 表示删除操作，dp[i][j-1] 表示插入操作
> 			}
> 
> 		}
> 	}
> 	return dp[n][m]
> }
> ```

1. 能不能讲下思路
2. 能不能降纬，从而获得空间上的优化
