### ISSUE TITLE
【每日一题】- 2019-10-10 - 76. 最小覆盖子串 

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#197]
给你一个字符串 S、一个字符串 T，请在字符串 S 里面找出：包含 T 所有字母的最小子串。

示例：

输入: S = "ADOBECODEBANC", T = "ABC"
输出: "BANC"
说明：

如果 S 中不存这样的子串，则返回空字符串 ""。
如果 S 中存在这样的子串，我们保证它是唯一的答案。

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/minimum-window-substring
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by Veveue** [comment]
认领

**Comment by azl397985856** [comment]
> 认领

done

**Comment by wangyuxiang0829** [comment]
```
#include <string>
#include <iostream>
#include <unordered_map>
using namespace std;
class Solution {
public:
    string minWindow(string s, string t) {
        int match = 0, min = 0, start = 0, m = s.size(), n = t.size();
        unordered_map<char, int> map;
        unordered_map<char, int> count;
        for (auto c : t)
            map[c]++;
        for (int i = 0, j = 0; j < m; ++j) {
            if (map.find(s[j]) != map.end() && ++count[s[j]] == map[s[j]]) match++;
            while (match == map.size()) {
                if (j - i + 1 < min || min == 0) {
                    min = j - i + 1;
                    start = i;
                }
                if (map.find(s[i]) != map.end() && count[s[i]]-- == map[s[i]]) match--;
                i++;
            }
        }
        return s.substr(start, min);
    }
};

int main() {
    cout << Solution().minWindow("aa", "aa") << endl;
}
```

**Comment by wangyuxiang0829** [comment]
> ```
> #include <string>
> #include <iostream>
> #include <unordered_map>
> using namespace std;
> class Solution {
> public:
>     string minWindow(string s, string t) {
>         int match = 0, min = 0, start = 0, m = s.size(), n = t.size();
>         unordered_map<char, int> map;
>         unordered_map<char, int> count;
>         for (auto c : t)
>             map[c]++;
>         for (int i = 0, j = 0; j < m; ++j) {
>             if (map.find(s[j]) != map.end() && ++count[s[j]] == map[s[j]]) match++;
>             while (match == map.size()) {
>                 if (j - i + 1 < min || min == 0) {
>                     min = j - i + 1;
>                     start = i;
>                 }
>                 if (map.find(s[i]) != map.end() && count[s[i]]-- == map[s[i]]) match--;
>                 i++;
>             }
>         }
>         return s.substr(start, min);
>     }
> };
> 
> int main() {
>     cout << Solution().minWindow("aa", "aa") << endl;
> }
> ```

基本的滑动窗口，C++实现，各位大佬帮忙看看能不能优化一下

**Comment by wangyuxiang0829** [comment]
```
#include <string>
#include <iostream>
#include <unordered_map>
using namespace std;
class Solution {
public:
    string minWindow(string s, string t) {
        int match = 0, min = 0, start = 0, m = s.size(), n = t.size();
        unordered_map<char, int> count;
        for (auto c : t)
            count[c]++;
        for (int i = 0, j = 0; j < m; ++j) {
            if (count.find(s[j]) != count.end() && count[s[j]]-- > 0) match++;
            while (match == t.size()) {
                if (j - i + 1 < min || min == 0) {
                    min = j - i + 1;
                    start = i;
                }
                if (count.find(s[i]) != count.end() && ++count[s[i]] > 0) match--;
                i++;
            }
        }
        return s.substr(start, min);
    }
};

int main() {
    cout << Solution().minWindow("aa", "aa") << endl;
}
```
优化了一下，只用了一个map

**Comment by maninbule** [comment]
class Solution {
public:
    unordered_map<char,int> mpt,mps;
    string minWindow(string s, string t) {
        int start = 0,w = 1000000007,sz,cur = 0;
        for(const auto &c:t) mpt[c]++;sz = mpt.size();
        int l = 0,r = 0;
        for(;r<s.size();r++){
            mps[s[r]]++; 
            if(mps[s[r]] == mpt[s[r]]) cur++;
            while(l<s.size() && cur == sz){
                    if(r-l+1 < w) start = l,w = r-l+1;
                    mps[s[l]]--;
                    if(mps[s[l]] == mpt[s[l]]-1) cur--;
                    l++;
                }
        }
        if(w == 1000000007) return "";
        else return s.substr(start,w);
    }
};

**Comment by maninbule** [comment]
```cpp
class Solution {
public:
    unordered_map<char,int> mpt,mps;
    string minWindow(string s, string t) {
        int start = 0,w = 1000000007,sz,cur = 0;
        for(const auto &c:t) mpt[c]++;sz = mpt.size();
        int l = 0,r = 0;
        for(;r<s.size();r++){
            mps[s[r]]++;
            if(mps[s[r]] == mpt[s[r]]) cur++;
            while(l<s.size() && cur == sz){
                if(r-l+1 < w) start = l,w = r-l+1;
                mps[s[l]]--;
                if(mps[s[l]] == mpt[s[l]]-1) cur--;
                l++;
            }
        }
        if(w == 1000000007) return "";
        else return s.substr(start,w);
    }
};
```

**Comment by maninbule** [comment]
认领

**Comment by Veveue** [comment]
```javascript
const minWindow = function(s, t) {
  let result = "";
  const map = {};
  t.split("").forEach(item => (map[item] = (map[item] || 0) + 1));
  let count = Object.keys(map).length;
  let l = 0,
    r = -1;
  while (r < s.length) {
    if (count === 0) {
      if (!result || r - l + 1 < result.length) {
        result = s.slice(l, r + 1);
      }
      if (map[s[l]] !== undefined) {
        map[s[l]]++;
      }
      if (map[s[l]] > 0) {
        count++;
      }
      l++;
    } else {
      r++;
      if (map[s[r]] !== undefined) {
        map[s[r]]--;
      }
      if (map[s[r]] === 0) {
        count--;
      }
    }
  }
  return result;
};
```

**Comment by azl397985856** [comment]
> ```c++
> class Solution {
> public:
>     unordered_map<char,int> mpt,mps;
>     string minWindow(string s, string t) {
>         int start = 0,w = 1000000007,sz,cur = 0;
>         for(const auto &c:t) mpt[c]++;sz = mpt.size();
>         int l = 0,r = 0;
>         for(;r<s.size();r++){
>             mps[s[r]]++;
>             if(mps[s[r]] == mpt[s[r]]) cur++;
>             while(l<s.size() && cur == sz){
>                 if(r-l+1 < w) start = l,w = r-l+1;
>                 mps[s[l]]--;
>                 if(mps[s[l]] == mpt[s[l]]-1) cur--;
>                 l++;
>             }
>         }
>         if(w == 1000000007) return "";
>         else return s.substr(start,w);
>     }
> };
> ```

抱歉前面有人认领了，就在你前面得留言

**Comment by azl397985856** [comment]
> 认领

抱歉有人认领了，就在你前面留的言

**Comment by azl397985856** [comment]
@Veveue  认领需要提交PR

**Comment by azl397985856** [comment]
# 效率不高的滑动窗口解法，但是好理解（Python3）

## 思路

常规的滑动窗口题目。 leetcode有很多类似题目。 不过这道题我们窗口内的Counter可以大于等于target。 target指的是Counter(t)。那么我们可以实现一个contains方法来进行判断，其他部分和普通的简单滑动窗口题目并没有大的差别


## Code
```
from collections import Counter
from collections import defaultdict


class Solution:
    def minWindow(self, s: str, t: str) -> str:
        l = 0
        ans = s + s
        n = len(s)
        target = Counter(t)
        counter = defaultdict(lambda: 0)

        def contains(counter, target):
            if len(counter) < len(target):
                return False
            for k in counter:
                if k not in target or counter[k] < target[k]:
                    return False
            return True

        for r in range(n):
            if s[r] in target:
                counter[s[r]] += 1
            while l < n and contains(counter, target):
                if r - l + 1 < len(ans):
                    ans = s[l:r + 1]
                if s[l] in target:
                    counter[s[l]] -= 1
                l += 1
        return "" if ans == s + s else ans
```
