### ISSUE TITLE
【每日一题】- 2019-10-15 - 36. 有效的数独

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#204]
判断一个 9x9 的数独是否有效。只需要根据以下规则，验证已经填入的数字是否有效即可。

数字 1-9 在每一行只能出现一次。
数字 1-9 在每一列只能出现一次。
数字 1-9 在每一个以粗实线分隔的 3x3 宫内只能出现一次。

![image](https://user-images.githubusercontent.com/12479470/66794561-90e86d00-ef34-11e9-941e-1d2850452ba8.png)

上图是一个部分填充的有效的数独。

数独部分空格内已填入了数字，空白格用 '.' 表示。

示例 1:

输入:
[
  ["5","3",".",".","7",".",".",".","."],
  ["6",".",".","1","9","5",".",".","."],
  [".","9","8",".",".",".",".","6","."],
  ["8",".",".",".","6",".",".",".","3"],
  ["4",".",".","8",".","3",".",".","1"],
  ["7",".",".",".","2",".",".",".","6"],
  [".","6",".",".",".",".","2","8","."],
  [".",".",".","4","1","9",".",".","5"],
  [".",".",".",".","8",".",".","7","9"]
]
输出: true
示例 2:

输入:
[
  ["8","3",".",".","7",".",".",".","."],
  ["6",".",".","1","9","5",".",".","."],
  [".","9","8",".",".",".",".","6","."],
  ["8",".",".",".","6",".",".",".","3"],
  ["4",".",".","8",".","3",".",".","1"],
  ["7",".",".",".","2",".",".",".","6"],
  [".","6",".",".",".",".","2","8","."],
  [".",".",".","4","1","9",".",".","5"],
  [".",".",".",".","8",".",".","7","9"]
]
输出: false
解释: 除了第一行的第一个数字从 5 改为 8 以外，空格内其他数字均与 示例1 相同。
     但由于位于左上角的 3x3 宫内有两个 8 存在, 因此这个数独是无效的。
说明:

一个有效的数独（部分已被填充）不一定是可解的。
只需要根据以上规则，验证已经填入的数字是否有效即可。
给定数独序列只包含数字 1-9 和字符 '.' 。
给定数独永远是 9x9 形式的。

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/valid-sudoku
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by ruoguang** [comment]
import java.util.*;

/**
 * 判断一个 9x9 的数独是否有效。只需要根据以下规则，验证已经填入的数字是否有效即可。
 *
 * 数字 1-9 在每一行只能出现一次。
 * 数字 1-9 在每一列只能出现一次。
 * 数字 1-9 在每一个以粗实线分隔的 3x3 宫内只能出现一次。
 */
public class Test {
    public static void main(String[] args) {
        System.out.println(test());
    }

    // 将二维数组转为map
    public static Map<String, Integer> arrToMap() {
        Map<String, Integer> map = new HashMap<String, Integer>();
        String[][] arr = new String[][]{
                {"5", "3", ".", ".", "7", ".", ".", ".", "."},
                {"6", ".", ".", "1", "9", "5", ".", ".", "."},
                {".", "9", "8", ".", ".", ".", ".", "6", "."},
                {"1", ".", ".", ".", "6", ".", ".", ".", "3"},
                {"4", ".", ".", "8", ".", "3", ".", ".", "1"},
                {"7", ".", ".", ".", "2", ".", ".", ".", "6"},
                {".", "6", ".", ".", ".", ".", "2", "8", "."},
                {".", ".", ".", "4", "1", "9", ".", ".", "5"},
                {".", ".", ".", ".", "8", ".", ".", "7", "9"}
        };
        for (int i = 0; i < arr.length; i++) {
            for (int j = 0; j < arr[i].length; j++) {
                if (arr[i][j] == ".") {
                    map.put(i + "," + j, null);
                } else {
                    map.put(i + "," + j, Integer.parseInt(arr[i][j]));
                }
            }
        }
        return map;
    }

    // 单元测试
    public static boolean util(List<Integer> list) {
        boolean flag = true;
        HashSet<Integer> set = new HashSet<Integer>();
        for (Integer integer : list) {
            set.add(integer);
        }
        if(list.size()!=set.size()){
            flag=false;
        }
        return flag;
    }

    public static boolean test() {
        boolean result=true;
        Map<String, Integer> map = arrToMap();
        // 1*9 x轴检查
        List<Integer> list = new ArrayList<Integer>();
        for (int i = 0; i < 9; i++) {
            for (Map.Entry<String, Integer> entry : map.entrySet()) {
                if (entry.getKey().split(",")[0].equals(i+"")){
                    if(entry.getValue()!=null){
                        list.add(entry.getValue());
                    }
                }
            }
            if(!util(list)){
                return false;
            }
            list.clear();
        }

        // 9*1 y轴检查
        for (int i = 0; i < 9; i++) {
            for (Map.Entry<String, Integer> entry : map.entrySet()) {
                if (entry.getKey().split(",")[1].equals(i+"")){
                    if(entry.getValue()!=null){
                        list.add(entry.getValue());
                    }
                }
            }
            if(!util(list)){
                return false;
            }
            list.clear();
        }
        // 3*3 块状检查
        int[][] sum = {{1,1}, {1,4}, {4,7}, {4,1}, {4,4}, {4,7}, {7,1}, {7,4}, {7,7}};
        for (int i = 0; i < 9; i++) {
            for (Map.Entry<String, Integer> entry : map.entrySet()) {
                int x = Integer.parseInt(entry.getKey().split(",")[0]);
                int y = Integer.parseInt(entry.getKey().split(",")[1]);
                if(Math.abs(x-sum[i][0])<=1&&Math.abs(y-sum[i][1])<=1){
                    if(entry.getValue()!=null){
                        list.add(entry.getValue());
                    }
                }
            }
            if(!util(list)){
                return false;
            }
            list.clear();
        }
        return result;
    }
}

**Comment by azl397985856** [comment]
@ruoguang 我帮你格式化了代码。 是否有兴趣领取一下题目呢？领取方式： https://github.com/azl397985856/leetcode

**Comment by ruoguang** [comment]
别人N(1) 我是N(3) 单思路是最原始的一种解法，然后再看力扣的大神解题和官方解题。

**Comment by azl397985856** [comment]
@ruoguang 你的解法确实很复杂， 可以优化的空间很大

**Comment by maninbule** [comment]
领取

```cpp
class Solution {
public:
    bool visrow[10],viscol[10],vis3x3[10];
    bool isValidSudoku(vector<vector<char>>& board) {
        for(int i  = 0;i<9;i++){
            memset(visrow,0,sizeof visrow);
            memset(viscol,0,sizeof viscol);
            for(int j = 0;j<9;j++){
                if(board[i][j]!='.'){
                    if(visrow[board[i][j]-'0']) return false;
                    else visrow[board[i][j]-'0'] = 1;
                }
                if(board[j][i]!='.'){
                    if(viscol[board[j][i]-'0']) return false;
                    else viscol[board[j][i]-'0'] = 1;
                }
            }
        }
        for(int i = 0;i<9;i+=3){
            for(int j = 0;j<9;j+=3){
                memset(vis3x3,0,sizeof vis3x3);
                for(int ii = i;ii<i+3;ii++){
                    for(int jj = j;jj<j+3;jj++){
                        if(board[ii][jj]!='.'){
                            if(vis3x3[board[ii][jj]-'0']) return false;
                            else vis3x3[board[ii][jj]-'0'] = 1;
                        }
                    }
                }
            }
        }
        return true;

    }
};
```
![image](https://user-images.githubusercontent.com/34187105/67632767-fa785c00-f8e2-11e9-8baa-b9fbfa07b1e0.png)

**Comment by azl397985856** [comment]
@maninbule 领取是要整理的哦 done

**Comment by maninbule** [comment]
@azl397985856 整理是什么意思？写题解吗？我到现在还没懂55555

**Comment by azl397985856** [comment]
@maninbule 我说你怎么老是领取。 原来不知道啊， 这里是领取的步骤：https://github.com/azl397985856/leetcode/tree/master/daily

**Comment by azl397985856** [comment]
使用hashmap 记录行，列和块出现的数字可以轻松解决。 空间换时间

Python:

```python
#
# @lc app=leetcode.cn id=36 lang=python3
#
# [36] 有效的数独
#

# @lc code=start


class Solution:
    def isValidSudoku(self, board: List[List[str]]) -> bool:
        rowSeen = {}
        colSeen = {}
        blockSeen = {}
        LEN = 9

        for i in range(LEN + 1):
            rowSeen[i] = {}
            colSeen[i] = {}
            blockSeen[i] = {}

        for i in range(LEN):
            for j in range(LEN):
                v = board[i][j]
                if v == '.':
                    continue
                if v in rowSeen[i]:
                    return False
                rowSeen[i][v] = True
                if v in colSeen[j]:
                    return False
                colSeen[j][v] = True
                if v in blockSeen[j // 3 + (i // 3) * 3]:
                    return False
                blockSeen[j // 3 + (i // 3) * 3][v] = True

        return True
        # @lc code=end

```
