### ISSUE TITLE
【每日一题】- 2019-10-16 - 166. 分数到小数

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#205]
给定两个整数，分别表示分数的分子 numerator 和分母 denominator，以字符串形式返回小数。

如果小数部分为循环小数，则将循环的部分括在括号内。

示例 1:

输入: numerator = 1, denominator = 2
输出: "0.5"
示例 2:

输入: numerator = 2, denominator = 1
输出: "2"
示例 3:

输入: numerator = 2, denominator = 3
输出: "0.(6)"

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/fraction-to-recurring-decimal
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by zhangjinyang** [comment]
认领

**Comment by azl397985856** [comment]
> 认领

done
