### ISSUE TITLE
【每日一题】- 2019-10-23 - 486. 预测赢家

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#212]
给定一个表示分数的非负整数数组。 玩家1从数组任意一端拿取一个分数，随后玩家2继续从剩余数组任意一端拿取分数，然后玩家1拿，……。每次一个玩家只能拿取一个分数，分数被拿取之后不再可取。直到没有剩余分数可取时游戏结束。最终获得分数总和最多的玩家获胜。

给定一个表示分数的数组，预测玩家1是否会成为赢家。你可以假设每个玩家的玩法都会使他的分数最大化。

示例 1:

输入: [1, 5, 2]
输出: False
解释: 一开始，玩家1可以从1和2中进行选择。
如果他选择2（或者1），那么玩家2可以从1（或者2）和5中进行选择。如果玩家2选择了5，那么玩家1则只剩下1（或者2）可选。
所以，玩家1的最终分数为 1 + 2 = 3，而玩家2为 5。
因此，玩家1永远不会成为赢家，返回 False。
示例 2:

输入: [1, 5, 233, 7]
输出: True
解释: 玩家1一开始选择1。然后玩家2必须从5和7中进行选择。无论玩家2选择了哪个，玩家1都可以选择233。
最终，玩家1（234分）比玩家2（12分）获得更多的分数，所以返回 True，表示玩家1可以成为赢家。
注意:

1 <= 给定的数组长度 <= 20.
数组里所有分数都为非负数且不会大于10000000。
如果最终两个玩家的分数相等，那么玩家1仍为赢家。

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/predict-the-winner
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by aaaaaabiao** [comment]
java 动态规划解法
```java
class Solution {
    public boolean PredictTheWinner(int[] nums) {
        //动态规划
        //dp[i][j] 代表i->j先手的比后手多的分数
        //当取左端num[i]时,dp[i][j] = nums[i] - dp[i+1][j]
        //当取右端num[j]时,dp[i][j] = nums[j] - dp[i][j-1]
        //当i == j时, dp[i][j] = num[i]
        
        int len = nums.length;
        int[][] dp = new int[len][len];
        for(int i = 0; i < len; i++) {
            dp[i][i] = nums[i];
        }
        
        for(int i = len-1; i >= 0; i--) {
            for(int j = i+1; j < len; j++) {
                dp[i][j] = Math.max(nums[i] - dp[i+1][j], nums[j] - dp[i][j-1]);
            }
        }
        return dp[0][len-1] >= 0;
    }
}
```

**Comment by azl397985856** [comment]
@aaaaaabiao  这个解法很棒，有兴趣领取一下么

**Comment by aaaaaabiao** [comment]
> @aaaaaabiao 这个解法很棒，有兴趣领取一下么
可以啊，但是怎么认领了，不太会玩，有文档吗？

**Comment by aaaaaabiao** [comment]
@azl397985856  可以啊，但是怎么认领呢？

**Comment by azl397985856** [comment]
@aaaaaabiao 这里有详细步骤： https://github.com/azl397985856/leetcode/tree/master/daily#%E8%AE%A4%E9%A2%86%E6%AD%A5%E9%AA%A4

**Comment by ruoguang** [comment]
``package com.ms.test;

/**
 * 给定一个表示分数的非负整数数组。 玩家1从数组任意一端拿取一个分数，随后玩家2继续从剩余数组任意一端拿取分数，然后玩家1拿，……。每次一个玩家只能拿取一个分数，分数被拿取之后不再可取。直到没有剩余分数可取时游戏结束。最终获得分数总和最多的玩家获胜。
 */
public class Test {
    public static void main(String[] args) {
        int[] ints = {1, 5, 233, 7};
        System.out.println(firstWinFlag(ints));
    }


    public static boolean firstWinFlag(int[] arr) {
        int sumA=0;
        int sumB=0;
        for (int i = 0; i < arr.length; i++) {
            if(arr[i]<arr[arr.length-1]){
                int temp=arr[i];
                arr[i]=arr[arr.length-1];
                arr[arr.length-1]=temp;
            }
            if(i%2==0){
                sumA+=arr[i];
            }else {
                sumB+=arr[i];
            }
        }
        return sumA>=sumB;
    }
}

**Comment by maninbule** [comment]
领取
【动态规划】
状态表示：`dp[i][j] = {first,second}`表示区间[i,j]中，前者最高得first分数，后者最高得second分
状态转移：`dp[i][j].first = max(nums[i]+dp[i+1][j].second,nums[j]+dp[i][j-1].second) `
`dp[i][j].second`选对应的`first，dp[i+1][j].first or dp[i][j-1].first`
状态初始值：`dp[i][i] = {nums[i],0}`

为什么是`nums[i]+dp[i+1][j].second`？
因为当前者选了`nums[i]`,后者肯定选`dp[i+1][j].first`,因为他优于`dp[i+1][j].second`
所以 前者：`nums[i]+dp[i+1][j].second`，后者：`nums[i]+dp[i+1][j].first`

我参考的题解视频：https://www.youtube.com/watch?v=WxpIHvsu1RI
```cpp
typedef pair<int,int> pii;
class Solution {
public:
    //pair<int,int> dp[1010][1010];
    bool PredictTheWinner(vector<int>& nums) {
        vector<vector<pii>> dp(nums.size(), vector<pii>(nums.size())); // 定义一个pair<int,int>类型的二维数组
        int len = nums.size();
        for(int i = 0;i<len;i++)  dp[i][i] = {nums[i],0};
        for(int k = 1;k<len;k++){
            for(int i = 0;i+k<len;i++){
                int j = i+k;
                int sum1 = nums[i]+dp[i+1][j].second,sum2 = nums[j]+dp[i][j-1].second;
                if(sum1 >= sum2) dp[i][j] = {sum1,dp[i+1][j].first};
                else dp[i][j] = {sum2,dp[i][j-1].first};
            }
        }
        return dp[0][len-1].first >= dp[0][len-1].second;
    }
};
```
![image](https://user-images.githubusercontent.com/34187105/67468337-e501f880-f67c-11e9-8df1-5d0a610328f0.png)

**Comment by azl397985856** [comment]
@maninbule done
