### ISSUE TITLE
【每日一题】- 2019-11-04 - 圆上任取三点构成锐角三角形的概率

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#223]
来自字节跳动的一道几何题

**Comment by muyids** [comment]
1/4

**Comment by wptercel** [comment]
>来自字节跳动的一道几何题

@azl397985856
>来自字节跳动的一道几何题

@azl397985856 1/4吗？确定一个点之后另两点必须都落在第一个点正对面的半圆弧上，概率就是1*1/2*1/2

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
