### ISSUE TITLE
【每日一题】- 2019-12-02 - 692. 前K个高频单词

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#244]
给一非空的单词列表，返回前 k 个出现次数最多的单词。

返回的答案应该按单词出现频率由高到低排序。如果不同的单词有相同出现频率，按字母顺序排序。

示例 1：

输入: ["i", "love", "leetcode", "i", "love", "coding"], k = 2
输出: ["i", "love"]
解析: "i" 和 "love" 为出现次数最多的两个单词，均为2次。
    注意，按字母顺序 "i" 在 "love" 之前。
 

示例 2：

输入: ["the", "day", "is", "sunny", "the", "the", "the", "sunny", "is", "is"], k = 4
输出: ["the", "is", "sunny", "day"]
解析: "the", "is", "sunny" 和 "day" 是出现次数最多的四个单词，
    出现次数依次为 4, 3, 2 和 1 次。
 

注意：

假定 k 总为有效值， 1 ≤ k ≤ 集合元素数。
输入的单词均由小写字母组成。
 

扩展练习：

尝试以 O(n log k) 时间复杂度和 O(n) 空间复杂度解决。

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/top-k-frequent-words
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by 18sby** [comment]
领取
js解法
![image](https://user-images.githubusercontent.com/47735184/69949233-15ff0400-152c-11ea-822e-3138e59568cd.png)
```javascript
var topKFrequent = function(words, k) {
  let map = new Map(),
        result = [];

  words.forEach((item) => {
    let num = map.get( item );
    if (num === undefined) {
      map.set( item, 1 );
    }
    else {
      map.set( item, num + 1 )
    }
  })

  map = Array.from( map );

  map.sort((a, b) => {
    return b[1] - a[1];
  });

  let start = 0, val = null;
  for (let i = 0; i < map.length; i++) {
    if (val === null) {
      val = map[i][1];
    }
    else {
      if (map[i][1] !== val) {
        // 拿出去排序，拿回来拼接
        let section = map.slice(start, i);
        section.sort( (a, b) => {
          return a[0] > b[0] ? 1 : -1;
        });
        map.splice(start, i - start, ...section);
        // 初始化 start end val
        start = i;
        val = map[i][1];
      }
    }
  }

  if (start !== null) {
    let section = map.slice(start, map.length);
    section.sort( (a, b) => {
      return a[0] > b[0] ? 1 : -1;
    });
    map.splice(start, map.length - start, ...section);
  }

  for (let i = 0; i < k; i++) {
    if (map[i]) {
      result.push( map[i][0] );
    }
  }

  return result;
};
```

**Comment by azl397985856** [comment]
@18sby done
