### ISSUE TITLE
LRU-cache 那道题的复杂度不是O(1) 吧

### ISSUE THREAD

**Issue by wuhaoyupku** [azl397985856/leetcode#250]
看里面有个 queue.filter 的操作，这个应该是扫了一遍吧，复杂度明显不是O(1)

**Comment by azl397985856** [comment]
原题地址： https://github.com/azl397985856/leetcode/blob/master/problems/146.lru-cache.md

---------

是的，不是O(1)

**Comment by azl397985856** [comment]
欢迎提交PR
