### ISSUE TITLE
【每日一题】- 2020-01-02 - 71. 简化路径

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#258]
以 Unix 风格给出一个文件的绝对路径，你需要简化它。或者换句话说，将其转换为规范路径。

在 Unix 风格的文件系统中，一个点（.）表示当前目录本身；此外，两个点 （..） 表示将目录切换到上一级（指向父目录）；两者都可以是复杂相对路径的组成部分。更多信息请参阅：Linux / Unix中的绝对路径 vs 相对路径

请注意，返回的规范路径必须始终以斜杠 / 开头，并且两个目录名之间必须只有一个斜杠 /。最后一个目录名（如果存在）不能以 / 结尾。此外，规范路径必须是表示绝对路径的最短字符串。

 

示例 1：

输入："/home/"
输出："/home"
解释：注意，最后一个目录名后面没有斜杠。
示例 2：

输入："/../"
输出："/"
解释：从根目录向上一级是不可行的，因为根是你可以到达的最高级。
示例 3：

输入："/home//foo/"
输出："/home/foo"
解释：在规范路径中，多个连续斜杠需要用一个斜杠替换。
示例 4：

输入："/a/./b/../../c/"
输出："/c"
示例 5：

输入："/a/../../b/../c//.//"
输出："/c"
示例 6：

输入："/a//b////c/d//././/.."
输出："/a/b/c"

**Comment by unclegem** [comment]
首先读题可以发现其中的.和/没有用处，只有字串和..有用。这样我们可以按/来切割字符串
遍历切割后的字符串数组，若字串长度>0（为了避免//这种情况切割后是个空字符串）并且不是.的字串压入栈中，若字串是..则将栈顶的字串弹出，直至遍历结束。
最后返回 / + 栈内元素之间用/分开

``` java
    public String simplifyPath(String path) {
        Stack<String> stack = new Stack<>();
        for (String str : path.split("/")) {
            if (str.equals("..")) {
                if (!stack.isEmpty())
                    stack.pop();
            } else {
                if (!str.isEmpty() && !str.equals("."))
                    stack.push(str);
            }
        }
        return "/" + String.join("/", stack);
    }
```

``` python
    def simplifyPath(self, path):
        """
        :type path: str
        :rtype: str
        """
        stack = []
        for string in path.split('/'):
            if string == '..':
                if len(stack) > 0:
                    stack.pop(-1)
            else:
                if string != "" and string != '.':
                    stack.append(string)
        return '/' + '/'.join(stack)
```

**Comment by Casper-Mars** [comment]
#include <iostream>
#include <stack>
#include <string>
#include <vector>


using namespace std;

vector<string> splitString(const string &str, const string &patten) {
    vector<string> result;
    if (str.empty()) {
        return result;
    }
    string tmp = str + patten;
    size_t pos = tmp.find(patten);
    size_t size = tmp.size();

    while (pos != string::npos) {
        string target = tmp.substr(0, pos);
        result.push_back(target);
        tmp = tmp.substr(pos + patten.size(), size);
        pos = tmp.find(patten);
    }
    return result;
}

string stackToString(stack<string> target, const string &spilt, bool reverse) {

    stack<string> tmp;
    string result;
    if (reverse) {
        while (!target.empty()) {
            tmp.push(target.top());
            target.pop();
        }
    } else {
        tmp = target;
    }
    while (!tmp.empty()) {
        string tmpStr = tmp.top();
        tmp.pop();
        result += spilt + tmpStr;
    }
    return result;
}


string simplifyPath(const string &path) {

    vector<string> paths = splitString(path, "/");
    if (paths.empty()) {
        return "";
    }
    stack<string> stacks;
    for (auto &path : paths) {
        if (path.empty() || path == ".") {
            continue;
        }
        if (path == "..") {
            if (!stacks.empty()) {
                stacks.pop();
            }
            continue;
        }
        stacks.push(path);
    }
    string tmp = stackToString(stacks, "/", true);
    return tmp.empty() ? "/" : tmp;
}

**Comment by WuYifanX** [comment]
```java
import java.util.ArrayDeque;
import java.util.Deque;

class Solution {
  public String simplifyPath(String path) {
    Deque<String> deque = new ArrayDeque<>();

    String[] pathArray = path.split("/");
    for (String s : pathArray) {
      if (s.equals("") || s.equals(".")) {
        continue;
      } else if (s.equals("..")) {
        if (!deque.isEmpty()) deque.pop();
      } else {
        deque.push(s);
      }
    }

    StringBuilder sb = new StringBuilder();
    if (deque.isEmpty()) return "/";

    while (!deque.isEmpty()) {
      sb.append("/");
      sb.append(deque.pollLast());
    }
    return sb.toString();
  }
}

```

**Comment by azl397985856** [comment]
# Python Solution with Stack 

上面@unclegem 说的非常好了。 


假设我们不考虑`..`。我们只需要以'/'将其划分成若干部分。 这个时候如果我们可以通过过滤""（空字符串）和`.`（一个点）然后重新join起来实现"没有多余斜杠"和“没有多余的.”,最后我们在前面加一个斜杠即可。

然后我们考虑加上`..`。由于`..`是指代上层目录，因此我们只需要把最近的一个目录（如果存在的话），从路径从移除即可。  “最近的一个目录”我们使用栈就很方便。

# Code

```python
class Solution:
    def simplifyPath(self, path: str) -> str:
        st = []
        tokens = path.split('/')
        for token in tokens:
            if token == '..' and len(st) > 0:
                st.pop()
            if token != '.' and token != '' and token != '..':
                st.append(token)
        return '/' + '/'.join(st)
```
