### ISSUE TITLE
【每日一题】- 2020-01-10 - 1300. 转变数组后最接近目标值的数组和

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#272]
给你一个整数数组 arr 和一个目标值 target ，请你返回一个整数 value ，使得将数组中所有大于 value 的值变成 value 后，数组的和最接近  target （最接近表示两者之差的绝对值最小）。

如果有多种使得和最接近 target 的方案，请你返回这些整数中的最小值。

请注意，答案不一定是 arr 中的数字。

 

示例 1：

输入：arr = [4,9,3], target = 10
输出：3
解释：当选择 value 为 3 时，数组会变成 [3, 3, 3]，和为 9 ，这是最接近 target 的方案。
示例 2：

输入：arr = [2,3,5], target = 10
输出：5
示例 3：

输入：arr = [60864,25176,27249,21296,20204], target = 56803
输出：11361
 

提示：

1 <= arr.length <= 10^4
1 <= arr[i], target <= 10^5

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/sum-of-mutated-array-closest-to-target
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by azl397985856** [comment]
# 二分查找

很容易看出这是一个二分查找，和[猴子吃香蕉](https://github.com/azl397985856/leetcode/blob/master/problems/875.koko-eating-bananas.md) 几乎一样。类似的题还有很多，比如[1011. 在 D 天内送达包裹的能力](https://github.com/azl397985856/leetcode/blob/master/problems/1011.capacity-to-ship-packages-within-d-days.md)

我们的核心目标是找出0 - max(arr) 之前的一个数字，这个数字可以使得我们的数组和距离target最近。这不就是有序序列查找指定值么？ 

# Python Code

```python
class Solution:
    def findBestValue(self, arr: List[int], target: int) -> int:
        l = 0
        r = 2 * max(arr)
        def sumNotGreater(v):
            res = 0
            for num in arr:
                if num > v:
                    res += v
                else:
                    res += num
            return res

        while l < r:
            mid = (l + r) // 2
            s = sumNotGreater(mid)
            if  s < target:
                l = mid + 1
            else:
                r = mid
        
        return l - 1 if abs(sumNotGreater(l - 1) - target) <= abs(sumNotGreater(l) - target) else l
```

**Comment by unclegem** [comment]
Java题解 简单明了

该方法并没用到二分，而是首先确定出遍历起始点（起始点为target / arr.length是因为：若起始点比该值还小，那么以该值为阈值求出的距离只会更大，没必要进行计算。），以该起始点作为阈值求出距离并和当前最小距离进行比较，接着不断+1，若出现当前计算的距离比当前最小距离大了，那么也就没有继续计算的必要了（因为后续只会更大）。
``` java 
    public int findBestValue(int[] arr, int target) {
        
        int start = target / arr.length, maxDis = Integer.MAX_VALUE, res = 0;
        for (;;) {
            
            int sum = getSum(arr, start);
            int curDis = Math.abs(sum - target);
            if (curDis < maxDis) {
                
                maxDis = curDis;
                res = start;
                start++;
            } else
                break;
        }
        
        return res;
    }

    public int getSum(int[] arr, int val) {

        int sum = 0;
        for (int num : arr)
            sum += Math.min(num, val);

        return sum;
    }
```
