### ISSUE TITLE
【每日一题】- 2020-01-13 - 求一根绳子被切两刀能组成一个三角形的概率。

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#273]
如题

**Comment by unclegem** [comment]
我们可以设绳长为1，设:
- 其中两段长为x, y且x, y都>0
- 故第三段长为1-x-y且>0

故可以在二维坐标轴画出一个三角形(由x=0;y=0;1-x-y=0围成)

要想构成三角形还要满足:
- x+y > 1-x-y => x+y > 0.5
- x+1-x-y > y => y < 0.5
- y+1-x-y > x => x < 0.5

再在图中画出这三条线围出的三角形(由x=0.5;y=0.5;x+y=0.5围成)

最终发现可行面积占总面积的1/4(几何概率)=>最终概率结果为1/4
