### ISSUE TITLE
【每日一题】- 2020-02-03 - 45.跳跃游戏 II

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#288]
给定一个非负整数数组，你最初位于数组的第一个位置。

数组中的每个元素代表你在该位置可以跳跃的最大长度。

你的目标是使用最少的跳跃次数到达数组的最后一个位置。

示例:

输入: [2,3,1,1,4]
输出: 2
解释: 跳到最后一个位置的最小跳跃数是 2。
     从下标为 0 跳到下标为 1 的位置，跳 1 步，然后跳 3 步到达数组的最后一个位置。
说明:

假设你总是可以到达数组的最后一个位置。

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/jump-game-ii
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by azl397985856** [comment]
## Greedy (Python)

贪婪算法。 每次我们都选取局部最优解。

比如： [2,3,1,1,4]， 我们可以从2出发，我们可以达到索引为1和索引为2的两个点,[2,**3**,**1**,1,4]。而我们应跳到索引为1的点，因为索引为1的点一定比索引为2的点跳的更远。（注意题目已经说明了，“假设你总是可以到达数组的最后一个位置。”）。 一句话概括就是**每次在可跳范围内选择可以跳地更远的**。

这里有一个题解讲的很明白，可以参考一下： https://leetcode-cn.com/problems/jump-game-ii/solution/xiang-xi-tong-su-de-si-lu-fen-xi-duo-jie-fa-by-10/

## Code

```python
#
# @lc app=leetcode.cn id=45 lang=python3
#
# [45] 跳跃游戏 II
#

# @lc code=start


class Solution:
    def jump(self, nums: List[int]) -> int:
        n = len(nums)
        cnt = 0
        furthest = 0
        end = 0
        for i in range(n - 1):
            furthest = max(furthest, nums[i] + i)
            if i == end:
                cnt += 1
                end = furthest

        return cnt

        # @lc code=end

```

**Comment by 3460741663** [comment]
认领，刚好这俩天刷到这俩道题

**Comment by azl397985856** [comment]
> 认领，刚好这俩天刷到这俩道题

好的
