### ISSUE TITLE
【每日一题】- 2020-02-07 - 对面顶点和相等的正方体

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#291]
输入一个含有8个数字的数组，判断有没有可能把这8个数字分别放到正方体的8个顶点上（如图所示），使得正方体上三组相对的面上的4个顶点的和都相等。

![](https://tva1.sinaimg.cn/large/0082zybply1gbpeov6thcj30f60bsmyj.jpg)

From: 何海涛. “剑指Offer:名企面试官精讲典型编程题.”

**Comment by azl397985856** [comment]
这相当于先得到a1、a2、a3、a4、a5、a6、a7和a8这8个数字的所有排列，然后判断有没有某一个的排列符合题目给定的条件，即a1＋a2＋a3＋a4＝a5＋a6＋a7＋a8，a1＋a3＋a5＋a7＝a2＋a4＋a6＋a8，并且a1＋a2＋a5＋a6＝a3＋a4＋a7＋a8。

我们考虑使用回溯法解决，关于通用的模板可以参考我的仓库78题

**Comment by codeLearnerHY** [comment]
老哥，有java的代码吗

**Comment by azl397985856** [comment]
> 老哥，有java的代码吗

可以提供呀。  Java不难的

**Comment by codeLearnerHY** [comment]
我学java没多久，所以想多学习一下，但是没有源代码。我写到以两个数为一组的形式输出的时候就不会写了。。所以想看看源代码



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lucifer"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 中午11:47
收件人:&nbsp;"azl397985856/leetcode"<leetcode@noreply.github.com&gt;;
抄送:&nbsp;"2365789114"<2365789114@qq.com&gt;;"Comment"<comment@noreply.github.com&gt;;
主题:&nbsp;Re: [azl397985856/leetcode] 【每日一题】- 2020-02-07 - 对面顶点和相等的正方体 (#291)



 
老哥，有java的代码吗
  
可以提供呀。  Java不难的

**Comment by azl397985856** [comment]
@codeLearnerHY  那倒不如你贴下代码

**Comment by codeLearnerHY** [comment]
public class ArraysUtils {
    List<Integer&gt; list=new ArrayList<&gt;();
    public static List<List<Integer&gt;&gt; demo=new ArrayList<&gt;();
    public ArraysUtils(List<Integer&gt; list){
        this.list=list;
    }
    public static List<List<Integer&gt;&gt; getArrays(ArraysUtils arraysUtils){
         if(arraysUtils.list.size()%2!=0){
             for(int x=0;x<arraysUtils.list.size()/2+1;x++){
                 if((x*2+2)<arraysUtils.list.size()){
                     demo.add(arraysUtils.list.subList(2*x,2*x+2));
                 }
                 else if((x*2+2)&gt;=arraysUtils.list.size()){
                     demo.add(arraysUtils.list.subList(2*x,arraysUtils.list.size()));
                 }
                 else if(arraysUtils.list.size()<2){
                     demo.add(arraysUtils.list.subList(0,arraysUtils.list.size()));
                 }
             }
             return demo;
         }
         for(int x=0;x<arraysUtils.list.size()/2;x++){
             if((2*x+2)<arraysUtils.list.size())
             demo.add(arraysUtils.list.subList(2*x,2*x+2));
             else if((2*x+2)==arraysUtils.list.size())
                 demo.add(arraysUtils.list.subList(2*x,arraysUtils.list.size()));
             else if(arraysUtils.list.size()<2){
                 demo.add(arraysUtils.list.subList(0,arraysUtils.list.size()));
             }
         }
         return demo;
    }
}
我写的是这样的，但是我不知道怎么将这些数可以去随机重复排列。
------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lucifer"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 中午11:55
收件人:&nbsp;"azl397985856/leetcode"<leetcode@noreply.github.com&gt;;
抄送:&nbsp;"2365789114"<2365789114@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [azl397985856/leetcode] 【每日一题】- 2020-02-07 - 对面顶点和相等的正方体 (#291)




@codeLearnerHY  那倒不如你贴下代码

**Comment by azl397985856** [comment]
@codeLearnerHY  代码都被转义了怎么看？

**Comment by codeLearnerHY** [comment]
不好意思老哥，我重新发一遍。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"lucifer"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月11日(星期三) 中午1:45
收件人:&nbsp;"azl397985856/leetcode"<leetcode@noreply.github.com&gt;;
抄送:&nbsp;"2365789114"<2365789114@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [azl397985856/leetcode] 【每日一题】- 2020-02-07 - 对面顶点和相等的正方体 (#291)




@codeLearnerHY  代码都被转义了怎么看？
