### ISSUE TITLE
《游程编码和哈夫曼编码》专题中，哈夫曼编码的示例有误。

### ISSUE THREAD

**Issue by Bert-Z** [azl397985856/leetcode#295]
- 示例图中的 **b** 不应该有从 **e** 指过去的箭头，并且 **b** 的值应该为1101，否则不满足哈夫曼编码的性质。
- 附上[专题链接](https://github.com/azl397985856/leetcode/blob/master/thinkings/run-length-encode-and-huffman-encode.md)
- 如果我的理解有问题，还望指正。

**Comment by azl397985856** [comment]
你说的完全正确，请问是否可以提交一个PR，并成为项目的贡献者呢？

**Comment by Bert-Z** [comment]
嗯嗯，好的。

**Comment by Bert-Z** [comment]
> 你说的完全正确，请问是否可以提交一个PR，并成为项目的贡献者呢？

嗯嗯，好的。
