### ISSUE TITLE
【每日一题】- 2020-03-13 - 盲人买袜子。

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#317]
他们都各自买了两对黑袜和两对白袜，八对袜子的布质、大小完全相同，而每对袜子都有一张商标纸连着。两位盲人不小心将八对袜子混在一起。他们每人怎样才能取回黑袜和白袜各两对呢？

**Comment by abnerLiuSir** [comment]
暴力破解， 把袜子都拆开 一人一只 哈哈

**Comment by seachenjy** [comment]
一个分四对，四对拆开为8支，和对方互换其中4支

**Comment by Dream-20-3-18** [comment]
找一个眼睛好的，让他进行分配，

**Comment by sk95120** [comment]
均匀分布。

**Comment by azl397985856** [comment]
@seachenjy 正解
