### ISSUE TITLE
【每日一题】- 2020-03-14 - 烧绳子

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#318]
烧一根不均匀的绳要用一个小时，如果要准确判断一个小时十五分钟，至少需要几根绳子？

注意：
- 每一根绳子虽然都可以烧一个小时，但均匀程度都不一样

**Comment by abnerLiuSir** [comment]
三根

1.  第一根点燃一头的同时，第二根两头同时点燃。
2.  点燃两头的绳子燃尽时，同时点燃第一根绳子的另一头 并开始计时
3. 等第一根绳子燃尽 再点燃第三根绳子的一头
4.  燃尽  一小时十五分钟
