### ISSUE TITLE
【每日一题】- 2020-03-19 - 733. 图像渲染

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#322]
有一幅以二维整数数组表示的图画，每一个整数表示该图画的像素值大小，数值在 0 到 65535 之间。

给你一个坐标 (sr, sc) 表示图像渲染开始的像素值（行 ，列）和一个新的颜色值 newColor，让你重新上色这幅图像。

为了完成上色工作，从初始坐标开始，记录初始坐标的上下左右四个方向上像素值与初始坐标相同的相连像素点，接着再记录这四个方向上符合条件的像素点与他们对应四个方向上像素值与初始坐标相同的相连像素点，……，重复该过程。将所有有记录的像素点的颜色值改为新的颜色值。

最后返回经过上色渲染后的图像。

示例 1:

输入: 
image = [[1,1,1],[1,1,0],[1,0,1]]
sr = 1, sc = 1, newColor = 2
输出: [[2,2,2],[2,2,0],[2,0,1]]
解析: 
在图像的正中间，(坐标(sr,sc)=(1,1)),
在路径上所有符合条件的像素点的颜色都被更改成2。
注意，右下角的像素没有更改为2，
因为它不是在上下左右四个方向上与初始点相连的像素点。
注意:

image 和 image[0] 的长度在范围 [1, 50] 内。
给出的初始点将满足 0 <= sr < image.length 和 0 <= sc < image[0].length。
image[i][j] 和 newColor 表示的颜色值在范围 [0, 65535]内。

题目地址： https://leetcode-cn.com/problems/flood-fill/

扩展：

- PS中的抠图功能，核心算法是怎么样的？

![image](https://user-images.githubusercontent.com/12479470/77025126-47acb580-69cb-11ea-8b8e-57124deaa6ab.png)
（Before）
![image](https://user-images.githubusercontent.com/12479470/77025140-5004f080-69cb-11ea-940c-24c4d2c1f2f6.png)
（After）

**Comment by beidan** [comment]
日常占楼看答案

**Comment by feikerwu** [comment]
一个简单的dfs
```js
/**
 * @param {number[][]} image
 * @param {number} sr
 * @param {number} sc
 * @param {number} newColor
 * @return {number[][]}
 */
var floodFill = function(image, sr, sc, newColor) {
  let oldColor = image[sr][sc]
  if (oldColor === newColor) {
    return image
  }
  // 上下左右
  const pairs = [
    [-1, 0],
    [0, 1],
    [1, 0],
    [0, -1]
  ]
  dfs(sr, sc)
  return image;

  // 坐标是否合法
  function isValid(x, y) {
    return x >= 0 && y >= 0 && x < image.length && y < image[0].length
  }

  function dfs( x, y) {
    if (image[x][y] !== oldColor) {
      return
    }
    image[x][y] = newColor
    for(let i = 0; i < pairs.length; i++) {
      const [newX, newY] = [x + pairs[i][0], y + pairs[i][1]]
      if (isValid(newX, newY)) {
        dfs(newX, newY)
      }
    }
  }
};
```
