### ISSUE TITLE
【每日一题】- 2020-03-25 - 足球排球和篮球

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#326]
一个班级60%喜欢足球，70%喜欢篮球，80%喜欢排球，问：三种球都喜欢占比最大可能有多少，最小可能有多少？即求三种球都喜欢的比例范围

**Comment by azl397985856** [comment]
（1）首先确定最多的一种情况，就是 60% 喜欢足球的人同时也喜欢篮球和排球，此时为三种球都喜欢的人的最大比例。

 （2）然后确定最小的一种情况，根据题目可以知道有 40%的人不喜欢足球，30%的人不喜欢篮球，20%的人不喜欢排球，因此有最多
     90% 的人三种球中有一种球不喜欢，因此三种球都喜欢的人的最小比例为 10%。 （70 + 60 - 100） + 80 - 100 = 10

 因此三种球都喜欢的人占比为 10%-60%

**Comment by nasty11pig** [comment]
三球都喜欢的最大值为50%
最小值为:30%

**Comment by MScofied** [comment]
> 三球都喜欢的最大值为50%
> 最小值为:30%

why
