### ISSUE TITLE
【每日一题】- 2020-03-30 -372. 超级次方

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#329]
你的任务是计算 ab 对 1337 取模，a 是一个正整数，b 是一个非常大的正整数且会以数组形式给出。

示例 1:

输入: a = 2, b = [3]
输出: 8
示例 2:

输入: a = 2, b = [1,0]
输出: 1024

https://leetcode-cn.com/problems/super-pow/

**Comment by azl397985856** [comment]
# 暴力（超时）
## 思路

这道题和[50.pow-x-n](https://github.com/azl397985856/leetcode/blob/master/problems/50.pow-x-n.md) 有点像，我直接复用代码。思路不清楚的可以先看下我的那篇文章，以下我会直接使用myPow，你可以把它当成系统内置的pow函数。

我们的思路是对b逐位计算myPow，然后结果相乘即可。 比如 a = 2, b = [1, 0]。

- 先计算 2 ** 0 = 1
- 再计算 2 ** 10 = 1024
- 相乘为 1 * 1024 = 1024

为了防止数值溢出，我们使用一个小技巧，即`(a * b) % k = (a % k)(b % k) % k`

## 代码
```python
class Solution:
    def myPow(self, x: int, n: int) -> int:
        if n < 0:
            return 1 / self.myPow(x, -n)
        ans = 1
        while n:
            if n & 1 == 1:
                ans *= x
            x *= x
            n >>= 1
        return ans

    def superPow(self, a: int, b: List[int]) -> int:
       	ans = 1
        mask = 1
        k = 1337
        for num in b[::-1]:
            ans = (ans % k) * (self.myPow(a, num * mask) % k) % k
            mask *= 10
        return ans
```

# 分治

## 思路

上面代码比较暴力。 实际上，对于 a = 2, b = [1, 0, 0, 0]。（以下简称f(2, 1000)）我们上面的方案会计算:

- 2 ** 0 = 1
- 2 ** 0 = 1
- 2 ** 0 = 1
- 2 ** 1000 = ...

而我们知道 f(2, 1000) 等价于 f(2, 100) * f(2, 10) 这样计算量就小了很多。 有了这个思路，我们可以使用递归的方式简单解决。

## 代码

```python
class Solution:
    def myPow(self, x: int, n: int) -> int:
        if n < 0:
            return 1 / self.myPow(x, -n)
        ans = 1
        while n:
            if n & 1 == 1:
                ans *= x
            x *= x
            n >>= 1
        return ans

    def superPow(self, a: int, b: List[int]) -> int:
        if not b: return 1
        k = 1337
        return (self.myPow(a, b.pop(-1)) % k) * (self.myPow(self.superPow(a, b) % k, 10) % k) % k
```

# 扩展
你可以使用迭代的方式来解决么？

**Comment by MrTrans** [comment]
首选也是递归！
