### ISSUE TITLE
【每日一题】- 2020-04-08 - 1367. 二叉树中的列表

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#340]
给你一棵以 root 为根的二叉树和一个 head 为第一个节点的链表。

如果在二叉树中，存在一条一直向下的路径，且每个点的数值恰好一一对应以 head 为首的链表中每个节点的值，那么请你返回 True ，否则返回 False 。

一直向下的路径的意思是：从树中某个节点开始，一直连续向下的路径。

 

示例 1：

![image](https://user-images.githubusercontent.com/12479470/78849670-b370c400-7a47-11ea-89dd-d627239b2e04.png)

输入：head = [4,2,8], root = [1,4,4,null,2,2,null,1,null,6,8,null,null,null,null,1,3]
输出：true
解释：树中蓝色的节点构成了与链表对应的子路径。
示例 2：

![image](https://user-images.githubusercontent.com/12479470/78849676-b8357800-7a47-11ea-8c65-c5eaf7616450.png)

输入：head = [1,4,2,6], root = [1,4,4,null,2,2,null,1,null,6,8,null,null,null,null,1,3]
输出：true
示例 3：

输入：head = [1,4,2,6,8], root = [1,4,4,null,2,2,null,1,null,6,8,null,null,null,null,1,3]
输出：false
解释：二叉树中不存在一一对应链表的路径。
 

提示：

二叉树和链表中的每个节点的值都满足 1 <= node.val <= 100 。
链表包含的节点数目在 1 到 100 之间。
二叉树包含的节点数目在 1 到 2500 之间。

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/linked-list-in-binary-tree
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by feikerwu** [comment]
dp方程:
![image](https://user-images.githubusercontent.com/39146693/78856151-7eb93880-7a58-11ea-9545-a7e52612947d.png)
```js
/**
 * Definition for singly-linked list.
 * function ListNode(val) {
 *     this.val = val;
 *     this.next = null;
 * }
 */
/**
 * Definition for a binary tree node.
 * function TreeNode(val) {
 *     this.val = val;
 *     this.left = this.right = null;
 * }
 */
/**
 * @param {ListNode} head
 * @param {TreeNode} root
 * @return {boolean}
 */
var isSubPath = function(head, root) {
  if (head === null) {
      return true
  }
  if (root === null) {
    return false
  }
  return dfs(head, root) || isSubPath(head, root.left) || isSubPath(head, root.right)
};

function dfs(head, root) {
  if (head === null) {
    return true
  }
  if (root === null) {
    return false
  }
  if (head.val !== root.val) {
      return false
  }
  return dfs(head.next, root.left) || dfs(head.next, root.right)
}
```
