### ISSUE TITLE
【每日一题】- 2020-04-17 最后剩下谁？

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#345]
1〜50号运动员按顺序排成一排。教练下令：“单数运动员出列！”剰下的运动员重新排队编号。教练又下令：“单数运动员出列！ ”如此下去，最后只剰下一个人，他是几号运动员？如果教练下的令是“双数运动员出列！”最后剰下的又是谁？

**Comment by azl397985856** [comment]
## 思路

如果是双数出列，那么由于1号从来都没有动过，因此剩下的是1号。

如果是单数数列，每次剩下的人的编号分别是$2^N$,其中N为轮数。因此最后剩下的人的编号为$2^N$,而由于每次人数减少一半，因此总的轮数为`Math.log2(n) >>> 0`，其中 >>> 0 为向下取整，为的是处理总人数为奇数的情况。 这题可以扩展到一般，给定任意人数，可以求出最后剩下的号码。 

## 代码

```js
function test(n) {
  return Math.pow(2, Math.log2(n) >>> 0);
}
```

时间和空复杂度实际上取决于 log2 和 pow的实现，而对于不同的CPU其时间复杂度不尽相同，以下是大致的复杂度。 pow的时间和空间复杂度近似$(1)$，log2的时间复杂度近似为$log log n$,空间复杂度近似为$O(log n)$

***复杂度分析***
- 时间复杂度：$O(log log n)$
- 空间复杂度：$O(log n)$

更多题解可以访问我的LeetCode题解仓库：https://github.com/azl397985856/leetcode  。 目前已经30K star啦。

大家也可以关注我的公众号《脑洞前端》获取更多更新鲜的LeetCode题解

![](https://pic.leetcode-cn.com/89ef69abbf02a2957838499a96ce3fbb26830aae52e3ab90392e328c2670cddc-file_1581478989502)

**Comment by bigfacecatkivi** [comment]
var oddOut = function(n){
	let arr = Array.from({length: n},(item, index)=> index+1);
	while(arr.length > 1){
		for(let i=arr.length-1; i >= 0; i--){
			if(i%2 == 0){
				arr.splice(i, 1);
			}
		}
	}
	return arr[0];
}

**Comment by suukii** [comment]
```js
function sukiTest(n) {
  let leap = 1
  while (leap < n / 2) {
    leap = 1 + leap * 2
  }
  return leap + 1
}
```
