### ISSUE TITLE
【每日一题】- 2020-04-27 - 多人运动

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#347]
已知小猪每晚都要约好几个女生到酒店房间。每个女生 i 与小猪约好的时间由 [si , ei］表示，其中 si 表示女生进入房间的时间， ei 表示女生离开房间的时间。由于小猪心胸开阔，思想开明，不同女生可以同时存在于小猪的房间。请计算出小猪最多同时在做几人的「多人运动」。

例子： 
Input ： [[ 0 , 30] ,[ 5 , 10 ] ， [15 , 20 ] ] 
OutPut ：最多同时有两个女生的「三人运动」

**Comment by Don2025** [comment]
`#include <bits/stdc++.h>
using namespace std;
#define up(i,a,b) for(int i = a; i <= b; i++)
#define ms(a,x) memset(a,x,sizeof(a))
#define girl pair<int,int>   //first开始时间,second结束时间
#define mp(x,y) make_pair(x,y)
const int INF = 0x3f3f3f3f;
const int maxn = 1001;   //小猪每晚最多约的女生数量

int main()
{
    ios::sync_with_stdio(false);
    cin.tie(0),cout.tie(0);
    int n;    //小猪今晚约了n个女孩
    cin >> n;
    vector<girl> v;
    up(i,1,n)
    {
        int bg,ed;
        cin >> bg >> ed;
        v.push_back(mp(bg,ed));
    }
    int cnt[maxn];    //cnt[i]记录i时刻的多人运动人数
    ms(cnt,0);
    int ans = -INF;
    up(i,0,n)    //枚举
    {
        up(j,v[i].first,v[i].second)
        {
            cnt[j]++;
            ans = max(ans,cnt[j]);
        }
    }
    cout << ans << endl;
    return 0;
}`

**Comment by azl397985856** [comment]
## 思路
- 按照女孩约会的开始时间进行一次升序排序

![](https://tva1.sinaimg.cn/large/007S8ZIlly1ge88uvjpc4j30ib022t8o.jpg)

- 然后用一个小顶堆，维护当前每个女孩约会的结束时间
![](https://tva1.sinaimg.cn/large/007S8ZIlly1ge88ugb91ij30ca06edfy.jpg)
- 然后当一个新的女孩出现的时候，判断一下是否和上一个女孩有重叠，如果有则入堆，即多人运动的人数+1。
- 堆的大小表示的就是多人运动的最大人数，返回堆的大小即可。 

## 代码（C++）

```C++
class Solution {
public:
    int np(vector<vector<int>>& intervals) {
        sort(intervals.begin(), intervals.end(), [](const vector<int>& a, const vector<int>&b){
            return a[0] < b[0];
        });
        priority_queue<int, vector<int>, greater<int>> heap;
        for (int i = 0; i < intervals.size(); i++) {
            // 没重叠，弹出堆顶元素，并维持最小堆的性质不变
            if (!heap.empty() && heap.top() <= intervals[i][0]) {
                heap.pop();
            }
            // 女孩++
            heap.push(intervals[i][1]);
        }
        return heap.size();
    }
};
```

**Comment by woshiZS** [comment]
`#include<vector>
#include<iostream>

using std::cout;
using std::endl;
class Solution{
public:
    int maxOnlineAmount(vector<vector<int>> nums){
        int min=INT_MAX,max=INT_MIN,ans=0;
        for(auto num:nums){
            min=num[0]<min?num[0]:min;
            max=num[1]>max?num[1]:max;
        }
        vector<int> timetable(max-min+1,0);
        for(auto num:nums){
            for(int i=num[0];i<num[1];i++)timetable[i]++;
        }
        return *std::max_element(std::begin(timetable),std::end(timetable));
    }
};
int main(){
    vector<vector<int>> nums{{0,30},{5,10},{15,20},{17,25}};
    Solution solu;
    cout<<solu.maxOnlineAmount(nums)<<endl;
    return 0;
}`
Brute Force is the best algorithm!

**Comment by cyea** [comment]
## js
```js
const mlc = (arr) => {
    const flatArr = arr.flat()
    const minT = Math.min(...flatArr)
    const maxT = Math.max(...flatArr)
    let TIME_PEOPLE_NUM = []
    arr.forEach((pt) => {
        for (let i = minT; i <= maxT; i++) {
            if (i >= pt[0] && i <= pt[1]) {
                TIME_PEOPLE_NUM[i] ? TIME_PEOPLE_NUM[i]++ : TIME_PEOPLE_NUM[i] = 1
            }
        }
    });
    return Math.max(...TIME_PEOPLE_NUM)
}
console.log(mlc([[0, 30], [5, 10], [8, 10], [15, 20], [10, 40]]))
```

> 不知道对不对，主要是想答下(狗头)

**Comment by pengyuhou** [comment]
class sports(object):
    def sport(self,nums):
        a = nums
        res = sorted(a,key=lambda x:x[0])
        stack = []
        count = 0
        for i in range(len(res)):
            count = max(count,len(stack))
            if not i:
                stack.append(res[i])
                continue
            if res[i][0]<=stack[-1][1]:
                stack.append(res[i])
            else:
                stack.pop()
                stack.append(res[i])
        return count

**Comment by pengyuhou** [comment]
`class sports(object):
    def sport(self,nums):
        a = nums
        res = sorted(a,key=lambda x:x[0])
        stack = []
        count = 0
        for i in range(len(res)):
            count = max(count,len(stack))
            if not i:
                stack.append(res[i])
                continue
            if res[i][0]<=stack[-1][1]:
                stack.append(res[i])
            else:
                stack.pop()
                stack.append(res[i])
        return count`

**Comment by pengyuhou** [comment]
`
class sports(object):
    def sport(self,nums):
        a = nums
        res = sorted(a,key=lambda x:x[0])
        stack = []
        count = 0
        for i in range(len(res)):
            count = max(count,len(stack))
            if not i:
                stack.append(res[i])
                continue
            if res[i][0]<=stack[-1][1]:
                stack.append(res[i])
            else:
                stack.pop()
                stack.append(res[i])
        return count















`

**Comment by xfxhn** [comment]
function num(arr) {
    const nums = arr.sort((a, b) => a[0] - b[0]);
    return nums.reduce((peoples, item) => {
        if (peoples.length && peoples[peoples.length - 1] <= item[0]) {
            peoples.pop();
        }
        peoples.push(item[1]);
        console.log(peoples)
        return peoples
    }, []).length
}

**Comment by xfxhn** [comment]
```function num(arr) {
    const nums = arr.sort((a, b) => a[0] - b[0]);
    return nums.reduce((peoples, item) => {
        if (peoples.length && peoples[peoples.length - 1] <= item[0]) {
            peoples.pop();
        }
        peoples.push(item[1]);
        console.log(peoples)
        return peoples
    }, []).length
}`

**Comment by xfxhn** [comment]
`function num(arr) {
    const nums = arr.sort((a, b) => a[0] - b[0]);
    return nums.reduce((peoples, item) => {
        if (peoples.length && peoples[peoples.length - 1] <= item[0]) {
            peoples.pop();
        }
        peoples.push(item[1]);
        console.log(peoples)
        return peoples
    }, []).length
}`

**Comment by xfxhn** [comment]
`
function num(arr) {
    const nums = arr.sort((a, b) => a[0] - b[0]);
    return nums.reduce((peoples, item) => {
        if (peoples.length && peoples[peoples.length - 1] <= item[0]) {
            peoples.pop();
        }
        peoples.push(item[1]);
        console.log(peoples)
        return peoples
    }, []).length
}

`

**Comment by xfxhn** [comment]
```
function num(arr) {
    const nums = arr.sort((a, b) => a[0] - b[0]);
    return nums.reduce((peoples, item) => {
        if (peoples.length && peoples[peoples.length - 1] <= item[0]) {
            peoples.pop();
        }
        peoples.push(item[1]);
        console.log(peoples)
        return peoples
    }, []).length
}
```

**Comment by olongfen** [comment]
package main

import (
	"fmt"
)

func main() {

	fmt.Println(maximalSquare([][]int{{0, 30}, {5, 10}, {8, 10}, {15, 20}, {10, 40}}))
}


func maximalSquare(matrix [][]int) int {
	var (
		maxCount = 0
	)

	f := func(n int, leave int, comeIn int) int {
		count := 1
		for i := 0; i < n; i++ {
			if comeIn <= matrix[i][1] {
				count++
			}
		}
		return count
	}
	for i := 1; i < len(matrix); i++ {
		if f(i, matrix[i][1], matrix[i][0]) > maxCount {
			maxCount = f(i, matrix[i][1], matrix[i][0])
		}
	}
	return maxCount + 1 // 算上小猪本人 +1
}

**Comment by LeisureGong** [comment]
```
	/**
	 * 对开始时间进行排序，如果相邻的时间没有重叠，则移除最早的那个时间
	 * 堆的大小即为最大并集（移除一个元素的同时也加入一个新元素,除非有新的更大size的并集，堆的大小才会改变）
	 *
	 * @param intervals [开始时间，结束时间]二维数组
	 * @return 最大的并集
	 * @date 2020/4/28
	 */
	public int maxCount(int[][] intervals){
		// 根据开始时间排序
		Arrays.sort(intervals, (o1, o2) -> o1[0] - o2[0]);
		// 小顶堆，保存结束时间
		PriorityQueue<Integer> minHeap = new PriorityQueue<Integer>();
		for(int i = 0;i < intervals.length;i++){
			//相邻时间没有重叠，则移除最早的结束时间
			if(!minHeap.isEmpty() && minHeap.peek() <= intervals[i][0]){
				minHeap.remove();
			}
			minHeap.add(intervals[i][1]);
		}
		return minHeap.size();
	}
```

**Comment by suukii** [comment]
### 思路

1. Sort the girls by their arrive times in ascending order. Assume that all girls don't have to left the room after they enter it until the next girl arrives and the former's leaving time has already passed.

2. Now the girls start walking into the room one by one according to their arrive times. When a girl is about to enter the room, the last girl has to check her schedule, and if she finds out that she has to take leave, she leaves the room. And the girl who arrived before her has to check her schedule too. This process goes on till all the girls left in the room are to stay according to their schedules or there's no girl left in the room, then the above mentioned girl can go into the room.

3. While the girls are entering and leaving the room, we keep a counter that records the maximum of the total number of girls staying in the room.

### 图解
 
![bc](https://user-images.githubusercontent.com/30331289/80552485-5ee2b800-89f9-11ea-920f-959a208afa49.png)

### 代码

```js
const bc = girls => {
  girls.sort((a, b) => a[0] - b[0])

  const stack = []
  let count = 0
  girls.forEach(g => {
    while (stack.length > 0 && stack[stack.length - 1][1] < g[0]) {
      stack.pop()
    }
    stack.push(g)
    count = Math.max(count, stack.length)
  });
  return `最多同时有${count}个女生的「${count + 1}人运动」`
}
```

**Comment by azl397985856** [comment]
@suukii 非常棒的题解， 仅次于小哥哥我啦。 

你的代码中关于stack 部分， 本质上是一个单调递减栈。 而由于每一个女孩入栈出栈次数最多一次。 因此时间复杂度是$O(N^2)$。而采用堆的做法，可以以更小的代价获取到最小值（即你的栈顶）。因此从时间复杂度上来说，采用堆的算法复杂度更加优秀。

以上

**Comment by suukii** [comment]
@azl397985856 唔...谢谢 lucifer 小哥哥的夸奖，我会继续努力向“更加优秀”的小哥哥靠近的，嗯。

**Comment by mxuran** [comment]
class Solution:
    def maxSubArray(self, nums: "list[int]") -> int:
        n = len(nums)
        res = [None for _ in range(n)]
        res[0] = nums[0]
        for i in range(1, n):
            res[i] = max(res[i-1] + nums[i], nums[i])
        return max(res)

if __name__ == '__main__':
    max_time = 50
    girls = [[0, 30], [5, 10], [15, 20]]
    girls_format = [0 for _ in range(max_time)]
    for i in girls:
        girls_format[i[0]] += 1
        girls_format[i[1]] -= 1
    # print(girls_format)
    t = Solution()
    print("女生数：", t.maxSubArray(girls_format))

**Comment by mxuran** [comment]
class Solution:
    def maxSubArray(self, nums: "list[int]") -> int:
        n = len(nums)
        res = [None for _ in range(n)]
        res[0] = nums[0]
        for i in range(1, n):
            res[i] = max(res[i-1] + nums[i], nums[i])
        return max(res) + 1


if __name__ == '__main__':
    max_time = 50
    girls = [[0, 30], [5, 10], [15, 20]]
    girls_format = [0 for _ in range(max_time)]
    for i in girls:
        girls_format[i[0]] += 1
        girls_format[i[1]] -= 1
    t = Solution()
    print(t.maxSubArray(girls_format))

**Comment by mxuran** [comment]
```
class Solution:
    def maxSubArray(self, nums: "list[int]") -> int:
        n = len(nums)
        res = [None for _ in range(n)]
        res[0] = nums[0]
        for i in range(1, n):
            res[i] = max(res[i-1] + nums[i], nums[i])
        return max(res) + 1


if __name__ == '__main__':
    max_time = 50
    girls = [[0, 30], [5, 10], [15, 20]]
    girls_format = [0 for _ in range(max_time)]
    for i in girls:
        girls_format[i[0]] += 1
        girls_format[i[1]] -= 1
    t = Solution()
    print(t.maxSubArray(girls_format))
```

**Comment by bat67** [comment]
好有趣的一道题😂，被同学发的链接吸引过来的，也来蹭一波热点😂。
初来乍到，不知道规矩，就先贴代码了，还请大佬们多多包涵指教~

```C++
#include<iostream>
#include<algorithm>
using namespace std;

struct node
{
	int t;      //开始结束时间
	int flag; //开始结束标记
}arr[100000]; 

int cmp(struct node x, struct node y)
{
	if(x.t == y.t)
	{
		return x.flag > y.flag;
	}
	return x.t < y.t;
}

int main()
{
	int n;
	cin >> n; //n个女孩
	for(int i=0; i<n; ++i)
	{
		cin >> arr[i].t >> arr[i+n].t; //[si, ei]
		arr[i].flag = 1;
		arr[i+n].flag = -1;
	}
	sort(arr, arr+n*2, cmp);
	int ans = -1, count = 0;
	for(int i=0; i<n*2; ++i)
	{
		count += arr[i].flag;
		ans = max(ans,count);
	}
	cout << ans <<endl;
        return 0;
}
```
大概思路就是，将所有女孩开始和结束的时间一起排序，求和时，出现开始的时间就加一，出现结束的时间就减一，求和过程中出现的最大值就是“最多同时有几个女生做「多人运动」”

**Comment by Nomyfan** [comment]
1. 先按照女陔进入房间的时间排序，也就是女孩按顺序进入房间。
2. 然后每个女孩进入房间的时候把超时（记录每个女孩的离开时间）的女孩赶出去（实际应该自己出去），然后自己进去，计算此时房间里还有多少人。
3. 重复2直到最后一个女孩进入房间。

```java
class Solution {
    public int mp(int[][] times) {
        Arrays.sort(times, Comparator.comparingInt(t -> t[0]));

        PriorityQueue<Integer> pq = new PriorityQueue<>();
        int girls = 0;
        for (int[] time : times) {
            while (!pq.isEmpty() && pq.peek() <= time[0]) {
                pq.poll();
            }
            pq.add(time[1]);
            girls = Math.max(girls, pq.size());
        }

        return girls;
    }
}
```

**Comment by xiaohuazi123** [comment]
> ```
> class Solution:
>     def maxSubArray(self, nums: "list[int]") -> int:
>         n = len(nums)
>         res = [None for _ in range(n)]
>         res[0] = nums[0]
>         for i in range(1, n):
>             res[i] = max(res[i-1] + nums[i], nums[i])
>         return max(res) + 1
> 
> 
> if __name__ == '__main__':
>     max_time = 50
>     girls = [[0, 30], [5, 10], [15, 20]]
>     girls_format = [0 for _ in range(max_time)]
>     for i in girls:
>         girls_format[i[0]] += 1
>         girls_format[i[1]] -= 1
>     t = Solution()
>     print(t.maxSubArray(girls_format))
> ```

py实现方式！

**Comment by azl397985856** [comment]
> > ```
> > class Solution:
> >     def maxSubArray(self, nums: "list[int]") -> int:
> >         n = len(nums)
> >         res = [None for _ in range(n)]
> >         res[0] = nums[0]
> >         for i in range(1, n):
> >             res[i] = max(res[i-1] + nums[i], nums[i])
> >         return max(res) + 1
> > 
> > 
> > if __name__ == '__main__':
> >     max_time = 50
> >     girls = [[0, 30], [5, 10], [15, 20]]
> >     girls_format = [0 for _ in range(max_time)]
> >     for i in girls:
> >         girls_format[i[0]] += 1
> >         girls_format[i[1]] -= 1
> >     t = Solution()
> >     print(t.maxSubArray(girls_format))
> > ```
> 
> py实现方式！

格式不对，参考我的

**Comment by MrTrans** [comment]
留个坑位

**Comment by aleafboat** [comment]
```
class Solution {
 public:
  /**
   * @param intervals: an array of meeting time intervals
   * @return: the minimum number of conference rooms required
   */
  int minMeetingRooms(vector<Interval>& intervals) {
    // Write your code here
    // 01根据会议开始时间从小到大排序。如果不排序。观察出来规律就无效
    sort(intervals.begin(), intervals.end(),
         [](Interval& a, Interval& b) { return a.start < b.start; });

    // 02从[0..i]判断历史会议由没有结束。
    //利用优先级队列符合这个特点。
    //最小如果还没结束，剩余根本不需要比较,如果结束了只需要返回一个就可以。
    priority_queue<int, vector<int>, greater<int>> smallHeap;
    // https://zh.cppreference.com/w/cpp/container/priority_queue

    for (auto it : intervals) {
      //判断历史会议，有结束的吗
      if (!smallHeap.empty() && it.start > smallHeap.top()) {
        smallHeap.pop();  //  【1,30】【1,10】---【15,20】
                          // a<b <c<d a<d
      }

      smallHeap.push(it.end);
    }

    return smallHeap.size();  //无重叠会议个数。
  }
};
```

**Comment by brodxie** [comment]
### 思路
只需要关注每个女孩的开始结束时间
### 代码
```python3
if __name__ == '__main__':
    girls = [(0, 30), (5, 10), (15, 20)]
    times = set()
    for girl in girls:
        times.add(girl[0])
        times.add(girl[1])
    ans = 0
    for time in times:
        num = 0
        for start, end in girls:
            num += int(time >= start and time <= end)
        ans = max(ans, num)
    print(ans)
```

**Comment by jameingh** [comment]
插眼👀

**Comment by yanglr** [comment]
对于这一题，没买力扣vip的小伙伴可以到lintcode提交代码，会议室 II https://www.lintcode.com/problem/919

**Comment by qiaohaoforever** [comment]
刚刚头条考的就是这！
