### ISSUE TITLE
【国际化】- 增加英文题解， 翻译中文题解

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#363]
目前主要两个方向：
1. 增加其他自然语言的题解（可以没中文），质量要求：https://github.com/azl397985856/leetcode/issues/369

2. 给其他自然语言（主要是中文）做翻译

具体步骤参考：https://github.com/azl397985856/leetcode/blob/master/CONTRIBUTING.md

优秀国际化 PR:

- [PR 401 @EvelynL09 ](https://github.com/azl397985856/leetcode/pull/401)
- [PR 395 by @suukii ](https://github.com/azl397985856/leetcode/pull/395)

**Comment by azl397985856** [comment]
目前优先级比较高的题解：

- https://github.com/azl397985856/leetcode/blob/master/problems/42.trapping-rain-water.md

- https://github.com/azl397985856/leetcode/blob/master/problems/198.house-robber.md

- https://github.com/azl397985856/leetcode/blob/master/problems/454.4-sum-ii.md

- https://github.com/azl397985856/leetcode/blob/master/problems/90.subsets-ii-en.md

**Comment by URpineapple** [comment]
454.4-Sum-ii.md

**Comment by azl397985856** [comment]
@URpineapple OK👌

**Comment by EvelynL09** [comment]
认领 https://github.com/azl397985856/leetcode/blob/master/problems/42.trapping-rain-water.md

**Comment by azl397985856** [comment]
@EvelynL09 done

**Comment by EvelynL09** [comment]
认领https://github.com/azl397985856/leetcode/blob/master/problems/198.house-robber.md

**Comment by azl397985856** [comment]
@EvelynL09 done  42 翻译的不错 👍

**Comment by suukii** [comment]
并查集

**Comment by EvelynL09** [comment]
认领[前缀树专题](https://github.com/azl397985856/leetcode/blob/master/thinkings/trie.md)

**Comment by azl397985856** [comment]
@EvelynL09 ok
