### ISSUE TITLE
【每日一题】- 2020-06-03 - 997. 找到小镇的法官

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#379]
## 题目描述

在一个小镇里，按从 1 到 N 标记了 N 个人。传言称，这些人中有一个是小镇上的秘密法官。

如果小镇的法官真的存在，那么：

小镇的法官不相信任何人。
每个人（除了小镇法官外）都信任小镇的法官。
只有一个人同时满足属性 1 和属性 2 。
给定数组 trust，该数组由信任对 trust[i] = [a, b] 组成，表示标记为 a 的人信任标记为 b 的人。

如果小镇存在秘密法官并且可以确定他的身份，请返回该法官的标记。否则，返回 -1。

 

示例 1：

输入：N = 2, trust = [[1,2]]
输出：2
示例 2：

输入：N = 3, trust = [[1,3],[2,3]]
输出：3
示例 3：

输入：N = 3, trust = [[1,3],[2,3],[3,1]]
输出：-1
示例 4：

输入：N = 3, trust = [[1,2],[2,3]]
输出：-1
示例 5：

输入：N = 4, trust = [[1,3],[1,4],[2,3],[2,4],[4,3]]
输出：3
 

提示：

1 <= N <= 1000
trust.length <= 10000
trust[i] 是完全不同的
trust[i][0] != trust[i][1]
1 <= trust[i][0], trust[i][1] <= N

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/find-the-town-judge
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

## 相关题目

- [【每日一题】- 2020-02-25 - 🔒277.搜寻名人](http://leetcode-solution.cn/everyday/312)

**Comment by chelseachen007** [comment]
``` js
var findJudge = function (N, trust) {
    let peoples = Array.from({ length: N + 1 }, v => ({ trust: 0, betrust: 0 }))
    trust.forEach(v => {
        let people = v[0]
        let betrust = v[1]
        peoples[people].trust += 1
        peoples[betrust].betrust += 1
    })
    return peoples.findIndex((v, index) => {
        if (index == 0) return false;
        return v.trust === 0 && v.betrust == N - 1;
    });
};
```

**Comment by huangruitian** [comment]
```js
//考察点，有向图
//法官不相信任何人，出度为0；
//任何人都相信法官，法官入度即为n-1
var findJudge = function (N = 4, trust = [[1,3],[1,4],[2,3],[2,4],[4,3]]) {
  let nodeList = Array.from(Array(N+1), v => ({ outDegree: 0, inDegree: 0 }))
  // [1, 3], 意思是说节点1出度是1，节点2入度是1
  // 计算一下每个节点的出度入度即可
  trust.forEach(([node, node2]) => {
    nodeList[node].outDegree++
    nodeList[node2].inDegree++
  })
  // 返回出度是0，入度是 N-1的节点
  return nodeList.findIndex(({outDegree, inDegree}) => {
     return !outDegree && inDegree == N - 1
  })
};
```

**Comment by azl397985856** [comment]
## 两个数组
### 思路
如果熟悉图的话，应该知道这是一道有向图问题。 并且法官👩‍⚖️ 实际上就是出度为0，入度为 N - 1的节点。

因此一个思路就是统计所有人的入度和出度信息，将满足**出度为0，入度为 N - 1的节点**输出。

这里用两个数组 in_degree 和 out_degree 分别记录入度和出度的信息，为了简单起见，我们初始化的数组长度为 N + 1，而不是 N。

具体算法如下：

- 遍历 trust，如果 trust[i] 为 [a, b] 说明 a 信任 b，那么更新 a 的出度 + 1，b 的入读 + 1。
- 遍历所有节点，将满足**出度为0，入度为 N - 1的节点**输出。

### 代码

```py
class Solution:
     def findJudge(self, N, trust):
        in_degree = [0] * (N + 1)
        out_degree = [0] * (N + 1)
        for a, b in trust:
            in_degree[b] += 1
            out_degree[a] += 1
        for i in range(1, N + 1):
            if in_degree[i] == N - 1 and out_degree[i] == 0:
                return i
        return -1
```

***复杂度分析***
- 时间复杂度：$O(N)$
- 空间复杂度：$O(N)$

## 一个数组

### 思路

上面的分析中指出了**法官👩‍⚖️ 实际上就是出度为0，入度为 N - 1的节点**。这固然没错，然而我们仍然可以换个角度来思考，**法官👩‍⚖️ 同样是 入度 - 出度 == N - 1 的点**，并且不是法官的人不可能是。

这样我们无需同时维护入度和出度的信息，转而维护`入读和出度的差值`即可。

### 代码

```py
class Solution:
     def findJudge(self, N, trust):
        count = [0] * (N + 1)
        for i, j in trust:
            count[i] -= 1
            count[j] += 1
        for i in range(1, N + 1):
            if count[i] == N - 1:
                return i
        return -1
```

***复杂度分析***
- 时间复杂度：$O(N)$
- 空间复杂度：$O(N)$

虽然时间复杂度没有变化，但是我们完成了常系数级别的优化，空间复杂度从 2 * N，下降到了 N。

更多题解可以访问我的LeetCode题解仓库：https://github.com/azl397985856/leetcode  。 目前已经30K star啦。

大家也可以关注我的公众号《力扣加加》获取更多更新鲜的LeetCode题解

![](https://tva1.sinaimg.cn/large/007S8ZIlly1gfcuzagjalj30p00dwabs.jpg)

**Comment by Liu821218213** [comment]
### 解题思路
**此处撰写解题思路新建一个N行2列的数组来存储每个节点的进出度**
注意边界
和是否需要-1

注意：is和==并不相同，判断值相等最好用==

### 代码

```python3
class Solution:
    def findJudge(self, N: int, trust: List[List[int]]) -> int:
        deg = [[0 for i in range(2)] for j in range(N)] 
        for a in range(len(trust)):
            deg[trust[a][0]-1][0] += 1
            deg[trust[a][1]-1][1] += 1
        for i in range(N):
            if deg[i][1] == N-1 and deg[i][0] == 0:
                return i+1
        return -1
            
```
