### ISSUE TITLE
【每日一题】- 2020-06-11 - 斜着遍历

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#390]
遍历是算法的基础。 我们平时看到的 DFS 和 BFS 都是搜索， 而搜索的核心就是遍历，而关键点就是遍历的方式。 从根本上说动态规划也是枚举所有的可能，而枚举就需要用到遍历。 

而平时遍历一个二维数组 martrix 的时候， 我们习惯的方式是按行从左到右或者从右到左遍历。 少有情况是按照列遍历， 更少有情况是斜着遍历。

那么这次就考考你， 怎么斜着遍历一个二维数组。 eg：

```
[
 [1,2,3],
 [4,5,6],
 [7,8,9],
]
```

需要按顺序返回 [3,2,6,1,5,9,4,8,7]

![image](https://user-images.githubusercontent.com/12479470/84337230-a00ae200-abcb-11ea-8f99-7019739e47f3.png)

扩展：

- 按照顺序 [7,8,4,9,5,1,6,2,3] 返回该怎么做？

![image](https://user-images.githubusercontent.com/12479470/84337238-a731f000-abcb-11ea-8f87-f30e3eb2876c.png)

- 按照顺序 [3,6,2,1,5,9,8,4,7] 返回该怎么做？

![image](https://user-images.githubusercontent.com/12479470/84337266-b749cf80-abcb-11ea-9c51-a72d6f84d7bd.png)

**Comment by huangruitian** [comment]
- 个人认为这是一道很考验基本功扎实与否的题目
- 第二第三种懒得写代码了，在第一种上扩充一个temp处理
- 代码比较初级，不过可以打开一下思路
```js
function enumMartrix(dir = 1){
  let martrix = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
  ]
  let n = martrix.length
  let res = []
  let x = 0
  let y = n - 1
  //标记第三种遍历方式
  let threeDir = 0; 
  while(y >= 0 && x < n){
    // 如何控制走呢？
    let tempX = x
    let tempY = y
    let temp = []
    // 控制斜线走呗
    while(tempX < n && tempY < n){
      temp.push(martrix[tempX++][tempY++])
    }
    // 三种遍历方式
    if(temp.length){
      if(dir == 1){
        res.push(...temp)
      }else if(dir == 2){
        res.push(...temp.reverse())
      }else{
        threeDir % 2 == 0 && res.push(...temp)
        threeDir % 2 == 1 && res.push(...temp.reverse())
        threeDir++
      }
    }
    // 当 x < y  时, y -= 1; 往前拉
    // 当 x >= y 时, x += 1; 往下推
    if(x < y){
      y -= 1
    }else{
      x += 1
    } 
  }
  return res
}
```
