### ISSUE TITLE
Wrong link for leetcode 820

### ISSUE THREAD

**Issue by jasonyanwenl** [azl397985856/leetcode#393]
The problem is "Short Encoding of Words" but the link in that markdown file is "Walking robot simulation". The markdown file is [here](https://github.com/azl397985856/leetcode/blob/master/problems/820.short-encoding-of-words.md)

**Comment by azl397985856** [comment]
fixed!thank u。and add more explanation

**Comment by jasonyanwenl** [comment]
Thanks!
