### ISSUE TITLE
【每日一题】- 2020-09-02 - 赤道开枪

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#422]
在赤道向头顶垂直开枪，子弹会砸到自己么？

**Comment by ZHAOXIN009** [comment]
https://www.youtube.com/watch?v=fLq7uqI9Vyo&vl=zh-Hans&ab_channel=%E6%9D%8E%E6%B0%B8%E4%B9%90%E8%80%81%E5%B8%88

朝天开枪，子弹掉下来会打中自己吗？李永乐老师讲角动量守恒

**Comment by azl397985856** [comment]
> [youtube.com/watch?v=fLq7uqI9Vyo&vl=zh-Hans&ab_channel=%E6%9D%8E%E6%B0%B8%E4%B9%90%E8%80%81%E5%B8%88](https://www.youtube.com/watch?v=fLq7uqI9Vyo&vl=zh-Hans&ab_channel=%E6%9D%8E%E6%B0%B8%E4%B9%90%E8%80%81%E5%B8%88)
> 
> 朝天开枪，子弹掉下来会打中自己吗？李永乐老师讲角动量守恒

哈哈 👍
