### ISSUE TITLE
【每日一题】- 2020-09-21 - 1250. 检查「好数组」

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#431]
给你一个正整数数组 nums，你需要从中任选一些子集，然后将子集中每一个数乘以一个 任意整数，并求出他们的和。

假如该和结果为 1，那么原数组就是一个「好数组」，则返回 True；否则请返回 False。

 

示例 1：

输入：nums = [12,5,7,23]
输出：true
解释：挑选数字 5 和 7。
5*3 + 7*(-2) = 1
示例 2：

输入：nums = [29,6,10]
输出：true
解释：挑选数字 29, 6 和 10。
29*1 + 6*(-3) + 10*(-1) = 1
示例 3：

输入：nums = [3,6]
输出：false
 

提示：

1 <= nums.length <= 10^5
1 <= nums[i] <= 10^9

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/check-if-it-is-a-good-array
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by azl397985856** [comment]
## 思路

关于裴蜀定理，大家可以参考[维基百科](https://zh.wikipedia.org/wiki/%E8%B2%9D%E7%A5%96%E7%AD%89%E5%BC%8F)

简单来说，对于a1,a2,a3,... an 的 n 个数， 一定存在 a1 * n1 + a2 * n2 + a3 * n3 + ... + an * nn = d 。 其中 n1,n2,n3...nn 是正整数， d 为 a1,a2,a3,... an 的 n 个数的[最大公约数](https://zh.wikipedia.org/wiki/%E6%9C%80%E5%A4%A7%E5%85%AC%E5%9B%A0%E6%95%B8)。

而力扣不值一道题用到了这个定理，比如 [365. 水壶问题](https://github.com/azl397985856/leetcode/blob/master/problems/365.water-and-jug-problem.md)

因此自然而然， 这道题就是 d 为 1 的裴蜀定理问题， 因此我们的算法就是 check 存不存在一个子数组，其最大公约数为 1。而这个复杂度仍然很高， 我们仍然需要枚举所有的子数组。 

实际上我们不需要， 因为如果数组 A 是数组 B 的子集的话，那么 A 的最大公约数是 1， B一定也是 1. 因此我们只需要求出整体的最大公约数即可。

## 代码（Python）

```py
class Solution:
    def isGoodArray(self, nums: List[int]) -> bool:
        a = nums[0]
        for num in nums:
            a = gcd(a, num)
        return a == 1
```

**复杂度分析**
- 时间复杂度：$O(N * log(total))$，其中 total 为 nums 数组数字之和。
- 空间复杂度：$O(1)$。

根据欧几里德算法的定理：两个整数的最大公约数等于**其中较小的那个数**和**两数相除余数**的**最大公约数**，我们可以通过递归，不断缩小两个数字，直到某个数字为 0，则另外一个数字为最大公约数。

```python
def gcd(a: int, b: int) -> int:
    return a if b == 0 else gcd(b, a % b)
```


更多题解可以访问我的LeetCode题解仓库：https://github.com/azl397985856/leetcode  。 目前已经35K star啦。

关注公众号力扣加加，努力用清晰直白的语言还原解题思路，并且有大量图解，手把手教你识别套路，高效刷题。


![](https://tva1.sinaimg.cn/large/007S8ZIlly1gfcuzagjalj30p00dwabs.jpg)

**Comment by my-hub30** [comment]
done 2020-9-22
