### ISSUE TITLE
【每日一题】- 2020-10-13 - 655. 输出二叉树

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#438]
在一个 m*n 的二维字符串数组中输出二叉树，并遵守以下规则：

行数 m 应当等于给定二叉树的高度。
列数 n 应当总是奇数。
根节点的值（以字符串格式给出）应当放在可放置的第一行正中间。根节点所在的行与列会将剩余空间划分为两部分（左下部分和右下部分）。你应该将左子树输出在左下部分，右子树输出在右下部分。左下和右下部分应当有相同的大小。即使一个子树为空而另一个非空，你不需要为空的子树输出任何东西，但仍需要为另一个子树留出足够的空间。然而，如果两个子树都为空则不需要为它们留出任何空间。
每个未使用的空间应包含一个空的字符串""。
使用相同的规则输出子树。
示例 1:

输入:
     1
    /
   2
输出:
[["", "1", ""],
 ["2", "", ""]]
示例 2:

输入:
     1
    / \
   2   3
    \
     4
输出:
[["", "", "", "1", "", "", ""],
 ["", "2", "", "", "", "3", ""],
 ["", "", "4", "", "", "", ""]]
示例 3:

输入:
      1
     / \
    2   5
   / 
  3 
 / 
4 
输出:
[["",  "",  "", "",  "", "", "", "1", "",  "",  "",  "",  "", "", ""]
 ["",  "",  "", "2", "", "", "", "",  "",  "",  "",  "5", "", "", ""]
 ["",  "3", "", "",  "", "", "", "",  "",  "",  "",  "",  "", "", ""]
 ["4", "",  "", "",  "", "", "", "",  "",  "",  "",  "",  "", "", ""]]
注意: 二叉树的高度在范围 [1, 10] 中。

题目地址：https://leetcode-cn.com/problems/print-binary-tree/

**Comment by azl397985856** [comment]
## 思路

我的思路是先构建出一个大小正确的空的矩阵， 然后 DFS 遍历树， 遍历的同时给矩阵填充数据。

问题的关键点有两个：

1. 我如何知道这个矩阵的大小
2. 如何遍历填充

### 如何知道矩阵的大小

矩阵的高就是树的高， 因此我们可以计算出树的高度即可。 计算树的高度是一个简单题目，我们可以使用 BFS 计算， 也可以使用 BFS 维护一个全局最大值。这里我用 DFS ：

```py
def getDepth(root):
            if not root:
                return 0
            return 1 + max(getDepth(root.left), getDepth(root.right))
```

矩阵的宽呢？ 我们发现， 矩阵的宽实际上和高是有关系的，不同的高，宽不同。相同的高宽度也是一样的。 

整棵树的宽实际上等于 1 + (左子树的宽) + (右子树的宽)，不难发现这是一个递归问题。

比如：

- 高度为 1 ，宽度是 1 + (1 + 1) ， 其中括号里面的 1 是左右子树的宽度，括号外面的是根的宽度。算出其宽为 3

- 高度为 2 ，由于已知高度为1 的宽是3。因此其宽度是 1 + (3 + 3) ， 其中括号里面的 3 是左右子树的宽度，括号外面的是根的宽度。
 
不难看出规律：

```py
        cols = 0
        for _ in range(d):
            cols = cols * 2 + 1
```

### 遍历的同时填充矩阵

这个不难， 我们只需要 dfs 的时候记录左右边界即可。 


核心逻辑：
```py
def dfs(node,r,  l, r):
            col = (l + r) >> 1
            grid[row][col] = str(node.val)
            dfs(node.left, l, col - 1)
            dfs(node.right, col + 1, r)
```


很多题目都是这样的， 比如构建二叉树，再比如归并排序等。

## 代码

代码支持： Python3

```py
class Solution:
    def printTree(self, root: TreeNode) -> List[List[str]]:
        def getDepth(root):
            if not root:
                return 0
            return 1 + max(getDepth(root.left), getDepth(root.right))
        d = getDepth(root)
        cols = 0
        for _ in range(d):
            cols = cols * 2 + 1
        grid = [["" for _ in range(cols)] for _ in range(d)]

        def dfs(node, row, l, r):
            col = (l + r) >> 1
            if not node:
                return
            grid[row][col] = str(node.val)
            dfs(node.left, row + 1, l, col - 1)
            dfs(node.right, row + 1, col + 1, r)
        dfs(root, 0, 0, cols - 1)
        return grid
```

**复杂度分析**
- 时间复杂度：$O(N)$
- 空间复杂度：$O(N)$

大家对此有何看法，欢迎给我留言，我有时间都会一一查看回答。更多算法套路可以访问我的 LeetCode 题解仓库：https://github.com/azl397985856/leetcode 。 目前已经 37K star 啦。
大家也可以关注我的公众号《力扣加加》带你啃下算法这块硬骨头。
![](https://tva1.sinaimg.cn/large/007S8ZIlly1gfcuzagjalj30p00dwabs.jpg)

**Comment by anxingle** [comment]
好快啊，我还没AC呢.....   题解就出来了。

**Comment by azl397985856** [comment]
> 好快啊，我还没AC呢..... 题解就出来了。

哈哈哈
