### ISSUE TITLE
思路分成三个部分

### ISSUE THREAD

**Issue by AlphaAlgorithms** [azl397985856/leetcode#44]
在思路的heading下, 现在有思路概要和图形演示, 
提议分成三个部分:
1, 思路概要
2, 图形演示
3, pseudocodes

**Comment by azl397985856** [comment]
关键是“不是所有的题目都有图的，更不要说伪代码啦”

**Comment by AlphaAlgorithms** [comment]
伪码好写, 图难画, 是不是伪码比图更有表达力.

**Comment by azl397985856** [comment]
> 伪码好写, 图难画, 是不是伪码比图更有表达力.

伪代码是不难写，但是有时候没有必要，尤其是代码很简洁的情况。

图的话有时候确实不知道怎么入手才能画明白
