### ISSUE TITLE
【每日一题】- 2020-10-26 - 375. 猜数字大小 II

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#445]
我们正在玩一个猜数游戏，游戏规则如下：

我从 1 到 n 之间选择一个数字，你来猜我选了哪个数字。

每次你猜错了，我都会告诉你，我选的数字比你的大了或者小了。

然而，当你猜了数字 x 并且猜错了的时候，你需要支付金额为 x 的现金。直到你猜到我选的数字，你才算赢得了这个游戏。

示例:

n = 10, 我选择了8.

第一轮: 你猜我选择的数字是5，我会告诉你，我的数字更大一些，然后你需要支付5块。
第二轮: 你猜是7，我告诉你，我的数字更大一些，你支付7块。
第三轮: 你猜是9，我告诉你，我的数字更小一些，你支付9块。

游戏结束。8 就是我选的数字。

你最终要支付 5 + 7 + 9 = 21 块钱。
给定 n ≥ 1，计算你至少需要拥有多少现金才能确保你能赢得这个游戏。

来源：力扣（LeetCode）
链接：https://leetcode-cn.com/problems/guess-number-higher-or-lower-ii
著作权归领扣网络所有。商业转载请联系官方授权，非商业转载请注明出处。

**Comment by azl397985856** [comment]
# 记忆化递归
## 思路

## 代码

```py
class Solution:
    def getMoneyAmount(self, n: int) -> int:
        @lru_cache(None)
        def dfs(l, r):
            if l == r: return 0
            if r - l == 1: return l
            ans = 0xffffff
            for  i in range(l, r + 1):
                ans  = min(ans, i + max(dfs(l, i - 1), dfs(i + 1, r)))
            return ans
        return dfs(1, n)
```

**复杂度分析**

- 时间复杂度：$O(N^2)$
- 空间复杂度：$O(N^2)$

大家也可以关注我的公众号《力扣加加》带你啃下算法这块硬骨头。

![](https://tva1.sinaimg.cn/large/007S8ZIlly1gfcuzagjalj30p00dwabs.jpg)

**Comment by JasonZ2z** [comment]
这题好难，难的是对“极大极小化”思想的理解和接受，就跟鸡蛋掉落一样……

**Comment by feikerwu** [comment]
> 这题好难，难的是对“极大极小化”思想的理解和接受，就跟鸡蛋掉落一样……

可以理解为我们都足够聪明的情况下，如何聪明的选择策略使你的损失最小
