### ISSUE TITLE
thinking\union-find.md 并查集小树挂大树union函数

### ISSUE THREAD

**Issue by mengyuqianxun** [azl397985856/leetcode#479]
带路径压缩的代码模板
    def union(self, p, q):
        if self.connected(p, q): return
        # 小的树挂到大的树上， 使树尽量平衡
        leader_p = self.find(p)
        leader_q = self.find(q)
        if self.size[leader_p] < self.size[leader_q]:
            self.parent[leader_p] = leader_q
            self.size[leader_p] += self.size[leader_q]
        else:
            self.parent[leader_q] = leader_p
            self.size[leader_q] += self.size[leader_p]
        self.cnt -= 1

这里if分支里，leader_p小于leader_q，前者是小树，self.parent[leader_p] = leader_q，小树挂靠大树没问题，但下面size的相加，却是小树的size加上大树的size。我觉得应该是加反了，self.size[leader_q] += self.size[leader_p],else分支也是一样的问题。

**Comment by azl397985856** [comment]
fixed
