### ISSUE TITLE
关于leetcode 206.reverse-linked-list中python脚本的multi assignments

### ISSUE THREAD

**Issue by afazhou** [azl397985856/leetcode#480]
你好，标题中提及的代码是以下循环部分中的赋值语句。以head为1→2→3→None
为例，第一轮循环走完后，从直观理解，cur.next 应为None（因循环之前prev为None），prev应为1→2→3。但实际结果是cur.next 为 3→None, prev 为   @@1→None，prev的赋值似乎收到了cur.next赋值的影响，请问此处多重赋值的执行顺序是什么？非常感谢。

class Solution:
    def reverseList(self, head: ListNode) -> ListNode:
        if not head: return None
        prev = None
        cur = head
        while cur:
            cur.next, prev, cur = prev, cur, cur.next
        return prev

**Comment by azl397985856** [comment]
1. 贴一下原文链接
2. 格式化下你的代码

**Comment by afazhou** [comment]
原文链接：
https://github.com/azl397985856/leetcode/blob/master/problems/206.reverse-linked-list.md

代码也在原文链接内：

![image](https://user-images.githubusercontent.com/49027564/106744370-a36f4400-665a-11eb-924e-8f3c3f35bfc1.png)

**Comment by azl397985856** [comment]
”第一轮循环走完后“什么叫第一轮循环？难道有第二轮？

**Comment by azl397985856** [comment]
问问题不要贴图，而是贴代码，方便复制

**Comment by azl397985856** [comment]
上面代码等同于：

```
t1 = prev
t2 = cur
t3 = cur.next
cur.next = t1
prev = t2
cur = t3

```

**Comment by afazhou** [comment]
感谢回答。
我说的‘第一轮’就是循环一次的意思，如果head是1→2→3，根据上述算法，需要三次循环才能reverse成3→2→1。
回到赋值的问题上来，还是以head为1→2→3为例，根据你提供的等效代码，在第一次循环中，当执行完 cur.next = t1后，cur.next为None，同时t2和cur都变为1→None，因此接着执行prev = t2之后，prev也变成1→None。
也就是说cur.next = t1的执行影响了prev = t2的赋值。
但是cur = t3却未受影响，这里我不理解，因为我认为t3也会随cur.next一起变成None，从而影响cur = t3这句的赋值。
