### ISSUE TITLE
【anki 使用】- 

### ISSUE THREAD

**Issue by Liuqibaa** [azl397985856/leetcode#488]
博主你好，我想自己制作 anki 卡片，但是发现代码不好插进入，直接打的话太丑了，就想知道博主是怎么插入代码块的

**Comment by azl397985856** [comment]
用的插件。 你可以搜索下 anki 代码高亮插件

**Comment by Liuqibaa** [comment]
好的，谢谢博主，我还发现了在 anki 中使用 markdown：https://zhuanlan.zhihu.com/p/137570649?utm_source=wechat_session
