### ISSUE TITLE
【每日一题】- 2021-04-19 -  拿小球

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#489]
这道题是群友贡献的。 类似的题目也有很多，套路都差不多。有的公司偶尔会考察这种智力题目，比如之前咱们每日一题的[赛马问题](https://github.com/azl397985856/leetcode/blob/master/daily/2019-07-08.md)。

题目描述：

有两堆球，一堆10个 一堆8个， 每次从中至少拿走一个（只能拿一堆） 上不封顶 拿走最后一个的输  两个人轮流拿 ，你先拿怎么赢

**Comment by 52js** [comment]
我：10-8 = 2

**Comment by benmo1602** [comment]
第一个人 ， 那个堆都无所谓， 剩余两个 就可以了 
。。。 
感觉 a 赢不了 ， 如果我是 第二个人 ， 直接来 盖楼博弈吧 我执黑棋

**Comment by azl397985856** [comment]
我先卷未敬。

这道题的核心在于每个人都必须拿至少一个。

因此我们可以选任意一堆（不妨称其为堆 A），使之**仅剩下两个**。这样对手只有三个选择：

- 选择拿堆 A 一个，我们将堆 B ** 拿完**
- 选择拿堆 A 两个, 我们将堆 B **拿到只剩一个。**
- 选择拿堆 B n 个（ 1 <= n <= 堆 B 的大小），如果 n == 堆 B 的大小，那么我们拿一个 A。否则将 B 拿完。

总之，就是先拿一堆只剩两个，并在下一次拿的时候给对手留一个。

**Comment by feikerwu** [comment]
后发制人

我们可以选任意一堆（不妨称其为堆 A），使之仅剩下两个。这样对手只有三个选择：

选择拿堆 A 一个，我们将堆 B 拿完
选择拿堆 A 两个, 我们将堆 B 拿到只剩一个。
选择拿堆 B n 个（ 1 <= n <= 堆 B 的大小），留下堆B剩X个，如果X为奇数，我们拿1个，如果X为偶数，我们拿两个，

即保证对手最先去动剩下2个的那堆

**Comment by benmo1602** [comment]
这道题是 谁取 玩球之后能保证 球剩余 2:2 那谁就赢了 ，

**Comment by gimlee** [comment]
对方拿B堆剩余2个，先手面对A堆2个，B堆2个，会输吧？

**Comment by gimlee** [comment]
@feikerwu

**Comment by feikerwu** [comment]
> @feikerwu
是的，我这答案有问题

**Comment by gimlee** [comment]
先手只要保证拿的过程中不出现面临选择(1,0),(2,2)这两种情况，就能赢

**Comment by gimlee** [comment]
😄，只需要让后手面对数量相等的球选择就能保证先手赢。

**Comment by wptercel** [comment]
反着推：假设要拿n轮。
轮数 | 球数
------------ | -------------
n | 1，0
n-1 | 2，0或1，x

那就比谁能抢先造成2，0或者1，x的配置。可以拿到其中一堆只剩一个球造成1，x。而2，0不可能。因为第一手无论怎么拿，只要不能得到2，0或者1，x对方就能立马得到
