### ISSUE TITLE
【每日一题】- 2021-04-26 - 交换比特

### ISSUE THREAD

**Issue by azl397985856** [azl397985856/leetcode#491]
交换比特

给一个 8 位 的 integer，让你每两位交换一次，并返回交换后的数。

```py

def swap_bits(x): 
  pass
```

**Comment by azl397985856** [comment]
参考答案：

```py
def swap_bits(x):
    return (x & 0b10101010) >> 1 | (x & 0b01010101) << 1
```

**Comment by likenow** [comment]
class Solution {
    func swap_bit(x: Int) -> Int {
        // Mask A - a, in binary, is 1010
        let maskA = 0xAA
        // Mask 5 -  5, in binary, is 0101
        let mask5 = 0x55;
        let r1 = (x & maskA) >> 1
        let r2 = (x & mask5) << 1
        let result = r1 | r2
        return result
    }

    func testSwapBit(x: Int) {
        print(swap_bit(x: x))
    }
}

Solution().testSwapBit(x: 7)
