### ISSUE TITLE
树专题中双色标记法后序和前序写反了

### ISSUE THREAD

**Issue by edte** [azl397985856/leetcode#529]
![image](https://user-images.githubusercontent.com/50194671/157024305-6dfbeca9-0f74-4c48-a5af-0437e642334c.png)

前序应该是 

push(right)
push(left)
push(root)

后序是 
push(root)
push(right)
push(left)

应该和正常递归写法倒序

**Comment by edte** [comment]
好吧，原来之前有 issue 已经提过了，不过作者还是没有改过来呀

**Comment by azl397985856** [comment]
<img width="528" alt="image" src="https://user-images.githubusercontent.com/12479470/157064234-47761a76-e290-48c2-9ea7-6174684ce250.png">
