### ISSUE TITLE
二分查找专题，寻找最左/右插入位置算法模板错误问题

### ISSUE THREAD

**Issue by HEROhaoyu** [azl397985856/leetcode#541]
算法题解：https://leetcode-solution-leetcode-pp.gitbook.io/leetcode-solution/thinkings/binary-search-2
1，寻找最左/右插入位置中，都没有考虑下标越界的情况（left>length , right<0）。
2，寻找最右插入位置的模板写错了，可能是因为例题都是寻找最左插入位置所以无人发现吧。

**Comment by azl397985856** [comment]
1. 不可能发生 left > length or right < 0 的情况

**Comment by azl397985856** [comment]
1.  下标越界问题，以最左插入位置为例，如果整个数组都没有满足条件的值，最终left返回的是length（最右同理）
这个你试了么？ 我的难道不是返回 length？ 而且你前面说的是 > length ，现在又说 == length？

**Comment by HEROhaoyu** [comment]
> 1. 下标越界问题，以最左插入位置为例，如果整个数组都没有满足条件的值，最终left返回的是length（最右同理）
>    这个你试了么？ 我的难道不是返回 length？ 而且你前面说的是 > length ，现在又说 == length？
> 2. 你没有理解最左最右二分。 建议看下 往期二分关于最左最右满足二分的讲解

我再看看吧，谢谢博主了。

**Comment by azl397985856** [comment]
https://github.com/azl397985856/leetcode/blob/master/91/binary-search.md

 先看看这个，然后自己代入试试。  如果还有问题再通过具体例子提 bug，谢谢

**Comment by HEROhaoyu** [comment]
> https://github.com/azl397985856/leetcode/blob/master/91/binary-search.md 这里有关于 《寻找最左边的满足条件的值》的描述
> 
> 先看看这个，然后自己代入试试。 如果还有问题再通过具体例子提 bug，谢谢。
> 
> eg: https://onlinegdb.com/07AcGSFj8H please check this

破案了博主(笑哭)，你最新发我的博客内容是没问题的，但是我看的是这个：https://leetcode-solution-leetcode-pp.gitbook.io/leetcode-solution/thinkings/binary-search-2#xun-zhao-zui-you-cha-ru-wei-zhi
这两个文档内容不一致。

**Comment by azl397985856** [comment]
不是。 这根本就是两篇文章

**Comment by azl397985856** [comment]
最左插入和最左满足本来就是两种。  

新的重置版删除了最左插入，我发你的旧的，让你看看，帮助你理解而已

**Comment by HEROhaoyu** [comment]
> 最左插入和最左满足本来就是两种。
> 
> 新的重置版删除了最左满足，我发你的旧的，让你看看，帮助你理解而已

!!!确实，我没注意到两个问题不一样，一个是“插入的位置”，一个是“满足条件的值”。
插入位置的话，确实不会越界，缩圈的方向也不一样，是我没考虑得当给弄混了。感谢博主愿意花时间回复我这个菜鸟。
