### ISSUE TITLE
link error

### ISSUE THREAD

**Issue by mershaywu77** [azl397985856/leetcode#545]
In the page https://github.com/azl397985856/leetcode/blob/master/problems/886.possible-bipartition.md
the link does not go to 886 https://leetcode.cn/problems/possible-bipartition/

**Comment by cherie-wuyajun** [comment]
这是来自QQ邮箱的自动回复邮件。您好，邮件已收到，我将会尽快给您回复。

**Comment by lording** [comment]
您好，您的来信已收到，我会尽快给您回复的！

**Comment by xiaosisong** [comment]
我已经收到了，会尽快查看的，谢谢
