### ISSUE TITLE
[695.最大岛屿面积,360,面试原题]【每日一题】

### ISSUE THREAD

**Issue by doublehearts** [azl397985856/leetcode#549]
给定一个用 n*m 矩阵表示的群岛的地图，其中 1 表示岛屿， 0 表示海洋，每个岛屿的水平或竖直方向相邻的岛屿可以视为连在一起的岛屿，每一块岛屿视为面积为 1 ，请问面积最大的岛屿是多少？

**Comment by cherie-wuyajun** [comment]
这是来自QQ邮箱的自动回复邮件。您好，邮件已收到，我将会尽快给您回复。

**Comment by lording** [comment]
您好，您的来信已收到，我会尽快给您回复的！

**Comment by xiaosisong** [comment]
我已经收到了，会尽快查看的，谢谢
