### ISSUE TITLE
已发布文章的代码错误

### ISSUE THREAD

**Issue by 1589864500** [azl397985856/leetcode#577]
暂时不知道往哪提交issue, 先交到这, 作者有幸看到再折叠掉好了.
简单来说, 状态压缩DP教程中len() API实现中, 判断len()==N的方法应该是 picked == (1 << (maxChoosableInteger + 1)) - 2, 而不是 -1, 因为二进制表示中的第0位默认为0, 全程没有用过. 因此len()==N时, picked应该等于1....10, 而不是1...11.

状态压缩DP教程 暂时只看到这两个网址
https://github.com/azl397985856/leetcode/blob/master/problems/464.can-i-win.md

https://mp.weixin.qq.com/s?__biz=MzI4MzUxNjI3OA==&mid=2247486874&idx=1&sn=0f27ddd51ad5b92ef0ddcc4fb19a3f5e&chksm=eb88c183dcff4895209c4dc4d005e3bb143cc852805594b407dbf3f4718c60261f09c2849f70&token=1227596150&lang=zh_CN#rd

**Comment by cherie-wuyajun** [comment]
这是来自QQ邮箱的自动回复邮件。您好，邮件已收到，我将会尽快给您回复。

**Comment by lording** [comment]
您好，您的来信已收到，我会尽快给您回复的！

**Comment by 1589864500** [comment]
您的邮件我已收到，谢谢！                                      --吴宇鹏

**Comment by fyyzkd** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by xiaosisong** [comment]
我已经收到了，会尽快查看的，谢谢

**Comment by azl397985856** [comment]
是的。  不过更具体地应该说： 在 [464. 我能赢吗](https://leetcode.cn/problems/can-i-win/) 这道题中应该 - 2， 因为最后一位没用到过。 其他题目大家要具体问题具体分析。
