### ISSUE TITLE
leetcode 的anki卡片只有10道题

### ISSUE THREAD

**Issue by chaixuqing** [azl397985856/leetcode#604]
leetcode 的anki卡片只有10道题，你是不是上传错文件了

**Comment by cherie-wuyajun** [comment]
这是来自QQ邮箱的自动回复邮件。您好，邮件已收到，我将会尽快给您回复。

**Comment by lording** [comment]
您好，您的来信已收到，我会尽快给您回复的！

**Comment by xiaosisong** [comment]
我已经收到了，会尽快查看的，谢谢

**Comment by chaixuqing** [comment]
@doublehearts @ztianming @andy814 @daydaygo @azl397985856 
Please solve this problem, which causes a lot of trouble for users.

**Comment by azl397985856** [comment]
没错，确实只有几道题。并不是所有题目都在 anki 上记录。

**Comment by xiaosisong** [comment]
我已经收到了，会尽快查看的，谢谢

**Comment by lording** [comment]
您好，您的来信已收到，我会尽快给您回复的！

**Comment by cherie-wuyajun** [comment]
这是来自QQ邮箱的自动回复邮件。您好，邮件已收到，我将会尽快给您回复。

**Comment by fyyzkd** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。
