### ISSUE TITLE
88.merge-sorted-array解法有误

### ISSUE THREAD

**Issue by chenquincy** [azl397985856/leetcode#62]
输入为
```
nums1: [1,2,3,0,0,0]
nums2: [2,5,6]
```
结果应该为：`[1,2,2,3,5,6]` , 而不是 `[1,2,3,3,5,6]`，图片有误
另外，题目中说的 nums1 的 `size is greater or equal to m + n` , 所以 `current` 初始值应该为 `m + n - 1` 而不是 `nums1.length - 1`，leetcode能跑过应该是没有 `greater` 的测试用例

**Comment by slogeor** [comment]
我也发现了，代码在leetcode运行是不通过的。

我写的代码也通过不了，谁有通过的代码share一下，谢谢

**Comment by kant-li** [comment]
经测试，三种语言的代码在LeetCode运行都通过，应该是确实没做greater测试用例，你这边是遇到什么其它问题吗？ @slogeor
